<?xml version="1.0" encoding="Windows-1251"?>
<!-- edited with XML Spy v3.5 NT (http://www.xmlspy.com) by alakim (mai) -->
<!DOCTYPE alph [
	<!ELEMENT alph (title, subtitle, section+)>
	<!ELEMENT p (#PCDATA | ref | footnote)*>
	<!ELEMENT section (p+)>
	<!ATTLIST section
	letter CDATA #REQUIRED
>
	<!ELEMENT subtitle (#PCDATA)>
	<!ELEMENT title (#PCDATA)>
	<!ELEMENT ref (#PCDATA)>
	<!ELEMENT footnote (#PCDATA)>
]>
<?xml-stylesheet type="text/xsl" href="alph.xsl"?>
<alph>
	<title>Ґлфави1тъ же сeй д¦0вный</title>
	<subtitle>си1цэ здЁ положи1хомъ</subtitle>
	<section letter="А">
		<p>Ѓзъ, ґдaмлz є3стествA сhй, тебЁ, nбоегw2 п0ла, є3стествA ґдaмлz, совётую: смирeнъ бyди.</p>
		<p>Ґдaмлz є3стествA сhй ми1ренъ бyди, пaмzтствуz прaведнагw њсуждeніz сл0во речeнное: ћкw землS є3си2, и3 въ зeмлю пaки п0йдеши. <ref>Быт. гл+а G</ref>
		</p>
	</section>
	<section letter="Б">
		<p>БGа познавaй, бlгодэ‰ніz є3гw2 разумёй, въ зaповэдехъ є3гw2 ходи2, да наслёдникъ бyдеши вёчныхъ бл†гъ.</p>
	</section>
	<section letter="В">
		<p>Вёруй въ бGа, вёруй бGу: воздержaніе всегдA во всeмъ и3мёй: при1снw пaмzтствуй смeртъ, и3 всёхъ вещeй и3змэнeніе и3 ни є3ди1нымъ чи1мъ ћтъ бyдеши въ мjрэ.</p>
	</section>
	<section letter="Г">
		<p>ГрэхA, t мaла дaже и3 до вели1ка блюди1сz: грёхъ тв0й пред8 nчи1ма всегдA и3мёй, ћкw да ўсeрднэ на всsкъ дeнь прилэжи1ши покаsнію.</p>
	</section>
	<section letter="Д">
		<p>Дeнь t днE къ горЁ добродётелей восходи2, ўсeрдіе ко ўсeрдію непрестaннw на всsкъ дeнь прилагaй, да ўпрaвиши тебE во всS стези6 прaвы.</p>
	</section>
	<section letter="Е">
		<p>Е$сть бо бlги6мъ надeжда, и3 всsкому трудY и3 п0двигу вёчный пок0й, и3 весeліе, въ грzдyщемъ вёцэ возмeздіе.</p>
	</section>
	<section letter="Ж">
		<p>Жи1знь вёчную, и3 грzд{щаz бlг†z при1снw да поминaеши, ћкw да къ си1мъ всегдA взимaеттисz сeрдце.</p>
	</section>
	<section letter="Ѕ">
		<p>Ѕэлw2 тщали1въ и3 ўсeрденъ въ твоeмъ звaніи и3 св0йствэ бyди, ћкw да не всyе и3знурsеши твою2 жи1знь.</p>
	</section>
	<section letter="З">
		<p>ЗрS твaрь чуди1сz, и3 творцY твaри славосл0віе приноси2, не къ твaри прилагaй тво‰ ч{вства, но къ бGу творцY всёхъ сeрдце и3 дyшу возводи2.</p>
	</section>
	<section letter="И">
		<p>И$же њ бlг0мъ и4мать ўсeрдіе, дaстсz є3мY: ґ и4же не и4мать, и3 є4же мни1тсz и3мёzй, в0зметсz t негw2.</p>
	</section>
	<section letter="І">
		<p>И$стину люби2, всsкіz лжи2 блюди1сz, да ўбэжи1ши прbр0ческагw речeніz: погуби1ши всsкаго глаг0лющаго лжY. <ref>Pал0м є7</ref>
		</p>
	</section>
	<section letter="К">
		<p>Къ бGу всегдA ќмъ тв0й, и3 дyшу непрестaннw возводи2, и3 никогдaже є3го2 t сeрдца и3 пaмzти твоeй и3спускaй, ћкw да всегдA съ ни1мъ соединeнъ бyдеши.</p>
	</section>
	<section letter="Л">
		<p>Люби1ти бGа t всегw2 сeрдца твоегw2, и3 t всеS крёпости твоеS потщи1сz: ћкw да и3звёстенъ спасeніz твоегw2 бyдеши, и3 всsкагw пристрaстіz земнaгw свободи1шисz.</p>
	</section>
	<section letter="М">
		<p>Мlтвэ непрестaннw прилэжи2: т0 бо є4сть некрaдомое сокр0вище, є4юже ўд0бь ћкw лёствицею, къ бGу взhдеши.</p>
	</section>
	<section letter="Н">
		<p>Не прилагaй сeрдца твоегw2 къ земны6мъ, да не ћкw с0ль њбуsеши, и3 вeсь непотрeбенъ kви1шисz: но къ бGу є3ди1ному сeрдце и3 дyшу твою2 пригвождeнну и3мёй, ћкw да неподви1жимь въ любви2 є3гw2 пребyдеши.</p>
	</section>
	<section letter="O">
		<p>Џнъ бо є4сть є3ди1нъ гDь, и3ст0чникъ всёхъ бл†гъ, и3 вёчныz жи1зни подaтель.</p>
	</section>
	<section letter="П">
		<p>Пaмzтствуй њ гDэ вhну, въ сeрдцэ и3 во ўстёхъ твои1хъ да пребывaетъ и4мz є3гw2 всегдA. Покаsнію при1снw прилэжи2, и3 на всsкъ дeнь тeплэ слезaми њмывaй дyшу твою2, да ўбэли1шисz пaче снёга, и3 не посрaмленъ лицeмъ пред8 гDемъ kви1шисz.</p>
	</section>
	<section letter="Р">
		<p>Рyцэ твои2 къ бGу наичaстэе въ мlтвэ воздэвaй ўсeрднэ, tтyду п0мощи всегдA взыскyz, да побэди1ши мhсленнаго ґмали1ка, си1рэчь, діaвола.</p>
	</section>
	<section letter="С">
		<p>Смeрть пaмzтствуz, скyпости и3 стэснeніz блюди1сz, да не невёріемъ и3 скyпостію ћтъ бhвши во врeмz и3сх0да, милосeрдіz б9іz двє1ри себЁ затвори1ши.</p>
	</section>
	<section letter="Т">
		<p>Ти1хъ, безтщеслaвенъ, и3 кр0токъ ко всёмъ бывaй, ћкw да и4стиненъ хrт0въ подражaтель и3 ўчени1къ без8 пор0ка kви1шисz.</p>
	</section>
	<section letter="U">
		<p>Ўнhніz и3 лёности ѕэлw2 храни1сz, ѓще х0щеши вск0рэ снискaти вёчное сокр0вище.</p>
	</section>
	<section letter="µ">
		<p>Ўсeрденъ и3 тeплъ къ бGу при1снw бyди, да причaстникъ бyдеши вёчныz жи1зни.</p>
	</section>
	<section letter="Ф">
		<p>ФараHна мhсленнаго въ водЁ слeзной потопи1ти тщи1сz, да не всегдA рaтуz г0нитъ тS.</p>
	</section>
	<section letter="Х">
		<p>ХrтA є3ди1наго взыскyй, да съ ни1мъ пребyдеши во вёки: взыскyющіи бо є3го2 њбрsщутъ вeлію ми1лость, и3 не лишaтсz всsкагw блaга.</p>
	</section>
	<section letter="T">
		<p>Nц7A и3 мaтерь, дрyги и3 ср0дники, и3 бGа бhти себЁ знaй: џнъ бо є4сть жи1зни начaло, и3 конeцъ всBмъ безконeчный.</p>
	</section>
	<section letter="Ц">
		<p>Цёль твоS и3 пристaнище гDь є3ди1нъ да бyдетъ, надeжда же и3 ўповaніе, прес™az є3гw2 люб0вь.</p>
	</section>
	<section letter="Ч">
		<p>ЧистотY и3 цэломyдріе, и4стиннw возлюби2, да прилэпи1шисz чи1стэ чи1стому: и3 чaсъ t часA покаsніz не tлагaй, да не погуби1ши врeмz и3справлeніz всyе во врeмz часA.</p>
	</section>
	<section letter="Ш">
		<p>Шестокри1лии добродётели, водружeни въ души2 твоeй всегдA да бyдутъ: си1рэчь, ўсeрдіе, друголю1біе, терпёніе, џбразъ бlгъ, разсуждeніе и3 люб0вь, и4миже ўд0бь на нб7о возвhсишисz.</p>
	</section>
	<section letter="Щ">
		<p>Щeдръ и3 ми1лостивъ ко всёмъ бyди, да ми1лостива и3 бlгоутр0бна гDа, въ дeнь стрaшнагw судA душЁ твоeй њбрsшеши. Е#ди1но сE въ пaмzти своeй и3мёй вhну, да бGу є3ди1ному всегдA ўгождaеши, и3 къ немY люб0вію при1снw да восх0диши.</p>
	</section>
	<section letter="Ю">
		<p>Ю$ностное п0хотное плотск0е безyміе t себE tметaй: премyдрости же д¦0вныz њ бз7э всегдA поучaйсz всеусeрднэ.</p>
	</section>
	<section letter="Я">
		<p>Ћрости, гнёва и3 ѕлосл0віz ѕэлw2 блюди1сz, да не помрачи1ттисz сердeчное џко.</p>
	</section>
	<section letter="W">
		<p>Њб8zдeніz и3 піsнства ѕэлw2 блюди1сz, да не во вс‰ ѕл†z всегдA впaдаеши.</p>
	</section>
	<section letter="O">
		<p>N§ескагw д¦0внагw наказaніz не преwбижaй, да не въ стезsхъ твои1хъ преткнeшисz.</p>
	</section>
	<section letter="P">
		<p>Pалмы2 и3 пёсньми бGа безпрестaннw славосл0ви, да при1снw сіE и4маши себЁ во ўтэшeніе.</p>
	</section>
	<section letter="F">
		<p>Фарісeйскагw тщеслaвнагw лицемёріz ѕэлw2 блюди1сz, да не °восплащeніе° <footnote>°мздY</footnote> твои1хъ бл†гъ себЁ тщеслaвіемъ здЁ воспріи1меши.</p>
	</section>
</alph>
