=== alvakim/spiritalph/xml/chapter.dtd
<!ELEMENT chapter (title, inscription, verse*)>
<!ATTLIST chapter
	part CDATA #REQUIRED
	chapt CDATA #REQUIRED
	verse_cnt CDATA #REQUIRED
>
<!ELEMENT title (#PCDATA)>
<!ELEMENT inscription (#PCDATA)>
<!ELEMENT verse (#PCDATA | ref | footnote)*>
<!ATTLIST verse
	number CDATA #REQUIRED
>
<!ELEMENT ref (#PCDATA)>
<!ELEMENT footnote (#PCDATA)>
<!--ELEMENT init (#PCDATA)-->
<!ELEMENT verses (title, subtitle, (inscription?, verse)*)>
<!ATTLIST verses
	nr CDATA #REQUIRED
	verse_cnt CDATA #REQUIRED
>
<!ELEMENT subtitle (#PCDATA)>

=== alvakim/spiritalph/xml/p24.xml
<?xml version="1.0" encoding="Windows-1251"?>
<!-- edited with XML Spy v3.5 NT (http://www.xmlspy.com) by alakim (mai) -->
<!DOCTYPE chapter SYSTEM "chapter.dtd">
<?xml-stylesheet type="text/xsl" href="chapter.xsl" ?>
<chapter part="3" chapt="2" verse_cnt="10">
	<title>ГлавA вторaz</title>
	<inscription>Њ є4же не зави1дэти комY ни во є3ди1ной вeщи сегw2 мjра.</inscription>
	<verse number="№">Не зави1ди, человёче, ниеди1ному комY њ благополучeніи сегw2 вёка преходsща: травa бо є4сть и3 цвётъ сeльный, всsка вeщь въ мjрэ: не зави1ди богaту и3 слaвну, ни въ земнhхъ сластeхъ гобзyющему: но въ добродётелехъ процвэтaющему благоyменъ подражaтель бyди. Почт0 бо њ настоsщихъ благополучeніихъ зави1дэти и4маши, понeже вс‰ въ мjрэ сeмъ врeмєннаz и3 тлBннаz сyть; и3ли2 богaтъ, во вёки ли тaкw пребyдетъ; Ѓще кто2 въ слaсти и3 благополучeніи и3з8wби1луетъ, всегдa ли; Но ѕэлw2 на мaло врeмz данA сі‰ сyть.</verse>
	<verse number="в7">Не зави1ди ќбw ни є3ди1ной вeщи сегw2 мjра: не зави1ди и3мёнію, богaтству же и3 слaвэ, и3 всsкому плотск0му наслаждeнію: не зави1ди сaну, чeсти, и3 всsкимъ дост0инствамъ: не зави1ди внёшнимъ жили1щамъ и3 прекрaсному здaнію, и3ли2 к0ему и3з8oби1лію: вс‰ бо сі‰ врeмєнна и3 тлBнна сyть: вс‰ преходsща, и3 ћкw дhмъ вск0рэ и3счезaющаz. Вс‰ здЁ њстaнутъ, вс‰ въ прaхъ и3 пeпелъ премэнsтсz, ничт0же бо є4сть вёчно на земли2: т0чію си6мъ благоразyмнw зави1ди, ѓще кто2 присоедини1тсz гDви, ѓще спод0битсz благодaти пrтaгw д¦а. Ѓще бо кто2 сію2 пріи1метъ, пaче всёхъ богaтыхъ и3 слaвныхъ богатёйшій и3 слaвнэйшій бyдетъ.</verse>
	<verse number="G">Не зави1ди, ѓще кого2 почитaютъ и3ли2 слaвzтъ, и3ли2 въ чeмъ кто2 и3з8wби1луетъ пaче тебE: но ћкw сHннаz мечт†ніz сі‰ бhти вмэнsй. Не зави1ди земны6мъ тлёющымъ вещeмъ, но къ нбcнымъ вёчнымъ сeрдце твоE вперeнно и3мёй: не сe бо є4сть бlгодaть б9іz, є4же њби1ловати въ чeмъ, и3ли2 почитaему бhти на земли2, но є4же пребhти всегдA при бз7э. Вeліz є4сть боsзнь и3 стрaхъ въ земнhхъ благополучeніzхъ њби1лующему: внезaпу бо приходи1ти њбhче тzжчaйшее и3змэнeніе, и3 tчуждeніе воспріsтыхъ благи1хъ си1хъ. Не мн0го ли бЁ прeжде слaвныхъ, богaтыхъ, хрaбрыхъ, премyдрыхъ; но днeсь сёхъ землS покры2, и3 пaмzть и4хъ ћкw небhвшихъ поги1бе. Человёкъ бо ћкw травA, днjе є3гw2 ћкw цвётъ сeльный, тaкw њцвэтeтъ: ћкw дyхъ пр0йде въ нeмъ, и3 не бyдетъ, и3 не познaетъ ктомY мёста своегw2, глаг0летъ прbр0къ <ref>Pал0мъ рв7</ref>.</verse>
	<verse number="д7">Вёждь, ћкw не ѕэлw2 зави1дэлъ бы є3си2, притв0ренъ вмaлэ џбразъ цaрскій не себЁ носsщему, и3ли2 въ с0нномъ мечтaніи богатёющему: нижE семY зави1дэлъ бы є3си2, ѓще бы кто2 на є3ди1нъ дeнь получи1лъ кyю п0честь, и3 посeмъ над0лзэ безчeствованъ бhлъ бы. Сегw2 рaди ѓще кто2 слaвитсz, да слaвитсz: ѓще кто2 богатёетъ, да богатёетъ: тh же себЁ внемли2, хвалsйсz, њ гDэ т0чію да хвaлитсz, богатёzй, њ гDэ да богатёетъ, гlетъ ґпcтолъ <ref>Корjн. за? Rє</ref>.</verse>
	<verse number="є7">Не зави1ди похвалsємымъ, ѓще кого2 похвалsютъ и3 слaвzтъ человёцы: но съ похвалsющими и3 ты2 благ0е похвалsй, ѕл0е же молчaніемъ преходи2. Не зави1ди, ѓще кого2 блажaтъ, и3 вси2 д0брэ глаг0лютъ њ нeмъ: нёсть бо постоsнно похвалeніе чlвёческое, но ѕэлw2 преврaтно: nвогдA похвалsютъ человёцы, nвогдa же ѕл†z вэщaютъ: џвіи слaвzтъ, џвіи же безчeстzтъ: џвымъ ўг0днw, други6мъ же нёсть: днeсь нёкто почтeнъ бhсть, ќтрw же внезaпу њбезчeстисz. Не пребывaетъ во є3ди1ной мёрэ, ни похвалA, нижE безчeстіе человёческое, но вс‰ вск0рэ и3змэнsютсz.</verse>
	<verse number="ѕ7">Почто2 бGу въ б9іихъ зави1диши; почто2 бGу въ б9іихъ возбранsеши; Не зави1ди ќбw ни є3ди1ному человёку ни въ чeмже но дост0инъ пред8 бGомъ бhти потщи1сz, да и3 ты2 пріи1меши по мёрэ, є3гHже дост0инъ бyдеши: нёсть бо лицемёріz ў бGа, но прaведное комyждо по достоsнію возмeздіе. Џнъ бо всёхъ человBкъ прaвою мёрою по возм0жному ўмёри, и3 ког0ждо своeю чeстію почтE, џваго си1це, џваго же си1це: но наипaче блажeнъ сeй человёкъ, є3мyже гDь бGъ є3гw2, глаг0летъ прbр0къ <ref>Pал0мъ lв</ref>.</verse>
	<verse number="з7">Почто2 зави1дэти и4маши всёхъ чeсти и3 дост0инствамъ; Понeже ты2 є3ди1нъ сaмъ вс‰ њб8sти не м0жеши. Почто2 зави1дэти и4маши благополучeнію сегw2 вёка преходsща; Понeже всE вск0рэ прех0дитъ, всE мимои1детъ. Мjръ сeй прелeстенъ є4сть, и3 вс‰ въ нeмъ превр†тна: днeсь почитaніе, ќтрw же ўкореніе: днeсь слaва,  ќтрw же безчeстіе: є3ли1кw кто2 наипaче прослaвитсz, вознесeтсz чeстію, толи1кw посeмъ наипaче њбезчeститсz: здё ли, и3ли2 nнaмw въ грzдyщей жи1зни.</verse>
	<verse number="}">Не бyди зaвистію снэдazй себE, ви1дz и3нёхъ, пaче тебE почитaемыхъ, слaвимыхъ, и3 богатёющихъ. БGъ бо вёсть свои1ми судьбaми кaкw твори1тъ: комY что2 дaруетъ, џнъ лyчше сaмъ вс‰ вёсть дaти. Не лёть ли господи1ну сотвори1ти во свои1хъ си2, ћкоже х0щетъ, џвому сіE, џвому же џно; не зави1ди ќбw, да не ўслhшиши њсуждeніz глaса глаг0люща: возми2 своE и3 и3ди2: не лёть ли ми2 въ мои1хъ сотвори1ти, ћкоже ѓзъ хощY, по є3ђльской при1тчи <ref>Матf. за? п7</ref>; Сегw2 рaди престaни зaвисти, tвeржи нeнависть, да не внЁ черт0га хrт0ва њстaнеши: зави1дzй бо ћкw ўбjйца сyдитсz, глаг0летъ нёкто.</verse>
	<verse number="f7">Зaвисть всемY ѕлY є4сть винA, всемy же благ0му супостaтъ. Зaвисти рaди кaінъ ѓвелz ўби2: и3сavъ їaкwва преслёдова, саyлъ дв7да гони2: и3 тмaми тє1мъ зaвисти рaди дёютсz ѕл†z въ мjрэ. Зaвисть и3 нeнависть затворsютъ нб7о, њслэплsютъ рaзумъ, помрачaютъ дyшу. њтzгчaютъ с0вэсть, њпечалsютъ бGа, веселsтъ бёсы. Зави1дzй, и3 ненави1дzй брaта своего2, во тмЁ х0дитъ, и3 не вёсть кaмw и4детъ, глаг0летъ ґпcлъ <ref>Їwaн. за? o7</ref>. Зaвисть не вёсть предпочитaти полє1знаz: и3дёже зaвисть и3 рвeніе, тaмw нестроeніе, гlетъ ґпccлъ <ref>Їaк. за? н7є</ref>.</verse>
	<verse number="‹">Тёмже во своeмъ t бGа ўстроeніи благодaренъ пребyди: на сeмъ преставaй, є4же ти2 бGъ дадE: вsщшымъ же тебE въ благополучeніи и3 чeсти не зави1ди: въ нeже звaнъ є3си2 и3 ўстр0енъ, въ т0мъ пребывaй, вsщшымъ же зави1стнэ не ревнyй. Предпочтeнныхъ t бGа и3 t человBкъ и3 ты2 предпочитaй, и3 ко tвэщaнію џнэмъ любeзенъ и3 смирeнъ бyди. Е#мyже бGъ что2 даровa, ты2 зaвистію не teмли: тебё же є4же не дано2 бhсть, г0рдостнэ себЁ не восхищaй: никт0же бо соб0ю пріsти что2 м0жетъ, ѓще не бGъ комY дaруетъ. Всsка влaсть и3 чeсть t бGа, ћкоже глаг0летъ ґпcлъ <ref>Ри1м. за? р№i</ref>.</verse>
</chapter>

=== alvakim/spiritalph/xml/p15.xml
<?xml version="1.0" encoding="Windows-1251"?>
<!DOCTYPE chapter SYSTEM "chapter.dtd">
<?xml-stylesheet type="text/xsl" href="chapter.xsl" ?>
<chapter part="2" chapt="3" verse_cnt="10">
	<title>ГлавA трeтіz</title>
	<inscription>Њ є4же не горди1тисz ни є3ди1ною вeщію въ вёцэ сeмъ.</inscription>
	<verse number="№">Не бyди г0рдъ и3 величaвъ, да не ўпод0бишисz бэсHмъ, не возноси1сz с®цемъ, да не сравнeнъ съ ни1ми бyдеши: но бyди кр0токъ и3 смирeнъ, да t гDа самaгw возвышeнъ бyдеши, и3 ѓгGлwмъ соедини1шисz. На ког0 бо воззрю2, но на кр0ткаго, смирeннаго и3 трепeщущаго мои1хъ словeсъ, гlетъ гDь; си1мъ бо т0чію наипaче рaзни сyть бёсове t ѓгGлwвъ, си1мъ и3 t бGа tпад0ша, є4же не пребhти и5мъ смирє1ннымъ, и3 благопокори6вымъ: ничт0же бо тaкw, не т0чію ў бGа, но и3 ў человBкъ мeрзостно є4сть, ћкоже возвышeніе и3 гордhнz: нижE си1це что2 любeзно и3 пріsтно, ћкоже кр0тость и3 смирeніе.</verse>
	<verse number="в7">Смирeнный и3 кр0ткій всегдA є4сть ми1ренъ, гордели1въ же и3 величaвъ всегдA є4сть мzтeженъ и3 смущeнъ. ГDь наставлsетъ крHткіz на сyдъ, и3 научaетъ смирє1нныz путє1мъ свои1мъ, глаг0летъ прbр0къ <ref>Pал0мъ к7д</ref>. Г0рдыхъ расточaетъ гDь мhслію с®ца, смирeнныхъ же и3 є3диномhсленныхъ вселsетъ въ д0мъ своеS бlгодaти. Благопокорли1въ бyди, да ўпод0бишисz ѓгGлwмъ. не горди1сz и3 над8 мaлымъ ки1мъ, да не и3 сaмъ t бGа tриновeнъ бyдеши: не возвышaйсz ни є3ди1ною вeщію, да не ни11зу поп0лзшисz вс‰ ѕл†z пострaждеши. Падeтъ бо г0рдый и3 сокруши1тсz, и3 не бyдетъ возставлszй є3го2, глаг0летъ прbр0къ <ref>Ї2ерем. гл+а }</ref>. Не ходи2 въ вели1кихъ, нижE въ ди1вныхъ пaче тебE, да не t бGа ўстрaншисz, въ сётехъ лови1телz врагA њстaнеши <ref>Pал0мъ Rл</ref>.</verse>
	<verse number="G">T безyміz и3 душeвныz слэпоты2 раждaетсz гордhнz: t рaзума жа и3 познaніz смирeніе. Ѓще бы себE и4стиннw познaлъ є3си2, не бы2 гордели1въ бhлъ є3си2: и3 ѓще себE и4стиннw познaеши, горди1тисz не бyдеши: но понeже є3щE себE д0брэ не знaеши, нижE, ћкw подобaетъ, разумёеши. Сегw2 рaди и3 мaлою вeщію, и3ли2 пaче њ ничес0мже безсловeснw горди1шисz: но ќбw познaй себE, г0рдъ и3 высокоyменъ сhй: гDь бо гHрдымъ проти1витсz, смирє1ннымъ же даeтъ бlгодaть, глаг0летъ соломHнъ <ref>При1т. гл+а G</ref>. Пріeмлетъ крHткіz гDь, смирsетъ же грBшныz гHрдыz до земли2: возн0ситъ смирє1нныz, снижaетъ же гHрдыz: пріeмлетъ смирeннагw и3 м†лаz, tметaетъ же г0рдагw и3 вели6каz: пріsтъ мытарS смирeннагw є3ди1но воздыхaніе, фарісeа же г0рдагw мнHгіz добродётєли tвeрже. Лyчше грёшникъ смирeнъ пред8 бGомъ, нeже прaведникъ гордели1въ: мeрзокъ бо є4сть пред8 бGомъ всsкъ высокосeрдый, глаг0летъ соломHнъ <ref>При1т. гл+а ѕ7i</ref>.</verse>
	<verse number="д7">ВездЁ бGъ tмeщетъ гHрдыz, пріeмлетъ же крHткіz: низлагaетъ си6льныz со престHлъ и3 возн0ситъ смирє1нныz: ѓлчущыz и3сполнsетъ бл†гъ, и3 богатsщыzсz tпущaетъ тщы2. И#збрA гDь смирє1нныz ґпcлы, гHрдыz же tвeрже фарісeи: tри1ну премyдрыz філос0фы, и3збрa же препрHстыz рhбари: tвeрже благорHдныz и3 вели1кіz кнsзи, и3збрa же смирє1нныz, їHсифа древодёлz, и3 прес™yю дв7у м™рь ўб0гую. тёмже њ прароди1тельномъ бlгор0діи никт0же горди1сz, вёдz, ћкw вси2 є3ди1наго и4мамы по бз7э прaoц7а ґдaма, прaхъ же и3 пeпелъ наслёдіе нaше. t земли1 бо взsти є3смы2, въ зeмлю же пaки п0йдемъ. Не возн0симсz є3ди1нъ на другaго: всёхъ бо нaсъ землS рaвнэ сравни1тъ, и3 комyждо дaстъ ўчaстіе своE.</verse>
	<verse number="є7">Ѓще и3 старёйшина є3си2 сaномъ, не бyди г0рдъ, да не и3 повинyющихсz тебЁ гордhни и3 дмeнію научи1ши: как0въ бо стaрэй є4сть, такови2 и3 повинyющіисz бhти њбык0ша. Старёйшій пaче всёхъ чlвBкъ, пaче же всеS твaри, гDь, џбразъ тебЁ соб0ю смирeніz показA: пріeмъ лeнтіонъ, н0ги ўченикHмъ ўмы2 <ref>Їwaн. за? м7д</ref>. зрaкъ рабA пріи1мъ, смири1лъ себE, бhсть послушли1въ дaже до смeрти, смeрти же крeстныz <ref>Філіп. за? ©м</ref>, ћкw да и3 мы2 таковA є3го2 зрsще смирsемсz. Не горди1сz ни є3ди1ною вeщію въ мjрэ сeмъ: вс‰ бо здЁ њстaнутъ, вс‰ въ прaхъ и3 пeпелъ премэнsтсz, тh же тaмw сaмъ є3ди1нъ п0йдеши, и3дёже зрёти не бyдутъ на сaны и3 вели6чества, но к0ждо по дэлHмъ свои1мъ t гDа воспріи1метъ.</verse>
	<verse number="ѕ7">Да не возн0сишисz врeменнымъ сaна почтeніемъ врeмененъ бо є4сть: нижE да горди1шисz старёйшинства вели1чествомъ, и3змэнsемо бо є4сть. не teмлетъ сaнъ є3стествA, нижE и3змэнsетъ старёйшинство человёчества: и3 старёйшій бо т0йжде человёкъ, ћкоже и3 пр0чіи: тazжде тлS и3 пeпелъ, ћкоже и3 и3нjи. Ничт0же вsщше и4мать старёйшій пaче малёйшагw, т0чію врeменное сaномъ почтeніе. Сегw2 рaди слaва твоS и3 п0честь старёйшинства да не прилагaетъ ти2 величaніz и3 гордhни: но пaче да ѕэлw2 смирsетъ тS: є3ли1кw бо, речE, вели1къ є3си2, толи1кw смирsйсz, да њбрsщеши пред8 гDемъ бlгодaть, глаг0летъ сірaхъ <ref>Сіра&lt;. гл+а G</ref>. данA тебЁ є4сть до врeмене сіS п0честь рaди и3справлeніz и3нёхъ, и3 чи1на nбhчнагw человёческагw, ґ не ћкw да си1мъ возн0сишисz, и3 величaешисz. Нёсть ќбw њ чес0мъ воздымaтисz старёйшинствомъ: всsка бо вeщь сyщаz и3змэнsющаzсz є4сть: є4сть бо сyщаz, ћкw не сyщаz, бывaющаz, ћкw не бывaющаz.</verse>
	<verse number="з7">Не тyне дaнный ти2 є4сть сaнъ и3 врeменное сегw2 мjра почитaніе, но да почитaнію твоемY и3 слaвэ покaжеши р†внаz во смирeніи и3справлє1ніz и3 добродётєли. Пaмzтствуй твоегw2 старёйшинства кончи1ну, и3 слaвы твоеS внезaпное и3змэнeніе, и3 никогдaже прельсти1шисz, нижE въ почитaніи и3 слaвэ человёческой ўповaніе своE полагaти бyдеши: ничт0же бо и4но сyть сі‰, т0чію снA неизвёстнэе, и3 лeда весeннагw прелeстнэе. не тyне дрeвніи любомyдрцы и3збрaвше старёйшину, и3 вэнцeмъ цaрскимъ вэнчaюще, запалsху лeнъ, и3 вhспрь мeщуще приглаг0лаху: тaкw слaва человёча вск0рэ ўгасaетъ, ћкоже лeнъ къ горЁ вhспрь вeрженный и3 блиснyвшій, и3 ѓбіе д0лу пaдшій, и3 внезaпу ўгaсшій.</verse>
	<verse number="}">Цaріе, кнsзи и3 велмHжи да не величaютсz свои1мъ вели1чествомъ: ничт0же бо пом0жетъ сaнъ и3 вели1чество во врeмz смeрти: пaче же вsщшую тzготY сотвори1тъ, да не глаг0летъ кто2, ѓзъ є4смь благор0денъ, сeй же худор0денъ: ѓзъ є4смь богaтъ, сeй же ўб0гъ: смeрть бо ког0ждо рaвнэ смири1тъ нaсъ, и3 tи1метъ всsко рaзнствіе. Во гр0бэ не познаю1тсz њбнажє1нныz кHсти, кто2 бЁ благор0денъ, и3ли2 худор0денъ, кто2 ни1щъ, и3ли2 богaтъ, кто2 слaвенъ, и3ли2 неслaвенъ. Сегw2 рaди да не возн0ситсz кто2 слaвою, сокр0вищемъ, и3 к0имълибо богaтствомъ: ничт0же бо взeмше, нaзи тaмw вси2 п0йдемъ: ничт0же при нaсъ њстaнетъ, т0чію и3справлє1ніz нaшz, ±же въ житіи2 сeмъ содёzхомъ.</verse>
	<verse number="f7">Почто2, человёче, всyе горди1тисz и4маши въ тлённой пл0ти; ничт0же бо дост0йно г0рдости и3 возношeніz въ себЁ њбрsщеши: t земли2 взsтъ є3си2, въ зeмлю же пaки п0йдеши. T ничесогw2 сотворeнъ є3си2, нижE пaки вёси, кaмw њбрати1шисz, и3 кyю чaсть получи1ши: тёмже не горди1сz слaвою, прех0дитъ бо: ни богaтствомъ, и3счезaетъ бо: ни благор0діемъ плотски1мъ, вси1 бо є3смы2 тлS и3 пeпелъ: ни си1лою, ни премyдростію, нижE красот0ю пл0ти: нёсть бо сіE t тебE: нижE чи1мъ и4нымъ: ничт0же бо и4маши своE, но вс‰ сyть б9іz. Ѓще бо рaзумомъ и3 премyдростію горди1тисz восх0щеши, но бGъ ю5 дадE: ѓще си1лою и3 красот0ю пл0ти, но бGъ вс‰ ўстр0и: ѓще и3мёніемъ и3ли2 богaтствомъ, но бGъ всE даровA: ѓще благор0діемъ, но вси2 є3смы2 землS и3 пeпелъ: ѓще сaна вели1чествомъ, но бGъ є4сть содержaй вс‰: ѓще к0имъ либо добродётельнымъ и3справлeніемъ, но бGъ пом0же, и3 ўстр0и и3 ўкрэпи2. Вс‰ б9іz сyть, ґ не нaша: не и4маши чи1мъ взимaтисz, нижE над8 и3нhми горди1тисz, но пaче всёхъ худёйша себE да вмэнsеши. БGу вс‰ сво‰ привмэнsй, да съ ни1мъ во всeмъ соединeнъ бyдеши: съ бGомъ бо вс‰ твоz бyдутъ, без8 бGа же всегw2 чyждь є3си2.</verse>
	<verse number="‹">Г0рдый не прaвымъ путeмъ и3 не простhмъ шeствуетъ но стр0потнымъ, тeрніz и3 волчцA и3сп0лненнымъ. Г0рдіи законопреступовaху до ѕэлA, и3 t зак0на твоегw2 ўклони1шасz, глаг0летъ прbр0къ <ref>Pал0мъ р}i</ref>. Сaмое сіE и4стое преступлeніе, и3 ўклонeніе t зак0на безсловeсное, въ непознaніи своеS нeмощи, возгордёніе є4сть. не чрeзъ и4но что2 тaкw бывaетъ преступлeніе и3 падeніе, ћкоже чрeзъ гордhню: ни въ чyвство чрeзъ и4но что бывaетъ сицево2 и3справлeніе, ћкоже чрeзъ смирeніе и3 простотY. И#дёже содёzсz подeніе, тaмw вс‰ предвари1ша. Гордhни рaди сатанаи1лъ съ нб7сE свeрженъ бhсть. Фарісeй вс‰ добродётєли разсhпа. Навуходон0соръ цaрствіz tпадE, и3 со скоты2, ћкw ск0тъ сeдмь лётъ травY kдE: и3 тhсzща тhсzщей падє1ніz гордhни рaди и3сполнeніе пріeмлютъ. тёмже пребyди смирeнъ, да бlгодaтію б9іею покрывaемь и3 сохранsемь всегдA бyдеши без8 всsкагw пор0ка, и3 без8 преткновeніz њбрsщешисz.</verse>
</chapter>

=== alvakim/spiritalph/xml/p14.xml
<?xml version="1.0" encoding="Windows-1251"?>
<!DOCTYPE chapter SYSTEM "chapter.dtd">
<?xml-stylesheet type="text/xsl" href="chapter.xsl" ?>
<chapter part="2" chapt="2" verse_cnt="10">
	<title>ГлавA вторaz</title>
	<inscription>Њ є4же не ѕэлw2 ўтэшaтисz њ почитaніи и3 слaвэ человёчестэй, прелє1стна бо сyть.</inscription>
	<verse number="№">Не желaй, человёче, почитaемь и3 слaвимь бhти t человBкъ, да не бжcтвенныz слaвы tтщети1шисz: не ѕэлw2 ўтэшaйсz њ слaвэ сегw2 мjра, да не внезaпу безчeстіемъ њгорчeнъ бyдеши: по слaвэ бо и3 по почитaніи человёчестэмъ ѓбіе послёдовати њбhче безчeстіе, по благополучeніи земн0мъ, тщетA: по весeліи и3 ўтэшeніи плотстёмъ, ск0рбь и3 печaль: и3змэни1теленъ бо є4сть вёкъ сeй, и3 вс‰ вє1щи въ нeмъ преходsщыz сyть. за благополучeніемъ бо и3змэнeніе и3 небlгополучeніе всегдA созади2 въ слёдъ шeствуетъ.</verse>
	<verse number="в7">Не прилагaй с®ца своегw2 къ почитaнію и3 слaвэ человёчестэй, лeстна бо є4сть, и3 маловрeменна: ничт0же є4сть и3звёстно въ мjрэ, т0чію є3ди1нъ бGъ, и3 є3гw2 предвёчнаz слaва: вс‰ бо въ мjрэ сeмъ премэнsютсz, и3 всsкое почитaніе и3 слaва съ ни1мъ прех0дитъ. Сегw2 рaди не ўтверждaй стопы2 ноги2 твоеS на си1хъ, да не ћкw на ледY весeнномъ њбтazвши прельщeнъ њстaнешисz тогдA, є3гдa к0е є4сть ти2 благополучeніе.</verse>
	<verse number="G">Не самолю1бствуй, нижE ѕэлw2 весели1сz њ почитaніи и3 величaніи сегw2 мjра: ћкw да посeмъ и3 њ безчeстіи є3гw2 не на мн0зэ њпечaлишисz. не ѕэлw2 ўтверждaйсz њ почитaніи є3гw2, ѓбіе бо внезaпу послёдуетъ є3мY и3змэнeніе: почитaніе бо и3 слaва человёческа под0бна є4сть џгненной и4скрэ, внезaпу блиснyвшей и3 ѓбіе ўгaсшей: и3ли2 г0вору водн0му во мгновeніи џка вознeсшемусz и3 ѓбіе разсёдшусz. Тёмже не ѕэлw2 ўтэшaйсz њ си1хъ: ўтэшazйбосz безсловeснw њ почитaніи и3 благополучeніи сегw2 мjра, вёждь, ћкw посeмъ внезaпу њ и3змэнeніи си1хъ безпaмzтнw скорбёти и4маши.</verse>
	<verse number="д7">Не пребывaетъ никогдaже во є3ди1ной мёрэ слaва и3 почитaніе человёческое: но ћкw лунA непрестaннw и3змэнsетсz. сегw2 рaди не ѕэлw2 ўтэшaйсz њ почитaніи и3 благополучeніи сегw2 мjра преходsщагw: ѓбіе бо въ слёдъ є3гw2 шeствуетъ внезaпное и3змэнeніе. мjръ сeй непостоsненъ є4сть, и3 вс‰ вє1щи въ нeмъ премэни1тельны: днeсь бо слaва и3 почитaніе, и3 ѓбіе внезaпу безчeстіе: днeсь весeліе и3 рaдость, и3 ѓбіе внезaпу ск0рбь и3 печaль: днeсь здрaвіе, и3 ѓбіе недyгъ: днeсь жив0тъ, и3 ѓбіе смeрть: и5хже мjръ мн0гажды мн0гими почитaньми и прелeстнw њбогати1лъ, си1хъ внезaпу смeрть њбнажи2.</verse>
	<verse number="є7">Не надымaйсz с®цемъ въ гордhни своeй, нижE величaйсz њ чlвёческомъ предпочитaніи, мнS себE вели1ка бhти: но ћкw сHннаz мечт†ніz, сі‰ бhти вмэнsй. Нёсть бо постоsнно почитaніе человёческое, но ѕэлw2 преврaтно. Почт0ша їудeє вётвьми и3 вaіами гDа, и3 ѓбіе њплевaша є3го2 <ref>Їwaн. за? м7а</ref>: предпочт0ша вмaлэ, и3 ѓбіе внезaпу њбезчeстиша є3го2. Е#ди1ни почитaху друзjи же Кrтъ на пропsтіе гот0вzху: преклонsху пред8 ни1мъ кwлёна, и3 ѓбіе по лани1тэ є3го2 ўдарsху. приглаг0лаху: рaдуйсz цRю2 їудeйскій: и4 ѓбіе терн0вый вэнeцъ не пречи1стую главY возлагaху <ref>Їwaн. за? н7f</ref>. Сицево2 є4сть почитaніе и3 слaва чlвёческаz. Почтeнъ бhсть цaрь дв7дъ чрeзъ самуи1ла на цaрствіе помaзаніемъ: и3 ѓбіе саyломъ гони1мь бsше <ref>№ Цаr гл+а ѕi</ref>. Почтeнъ бhсть t царS ґртаxeрxа пaче всёхъ кнzзeй ґмaнъ, и3 ѓбіе повёшенъ бhсть <ref>Е#сfi> гл+а з7</ref>, внезaпное є4сть и3змэнeніе бlгополучeніе и3 прочитaніе чlческое.</verse>
	<verse number="ѕ7">Ѕлохи1тростенъ є4сть мjръ, и3 є3гw2 почит†ніz: є3гдA бо человёкъ въ благодeнствіи є4сть, вси2 почитaютъ и3 слaвzтъ є3го2: є3гдa же въ презрёніи, вси2 tвращaютсz. Е#гдA во благополyчіи, мн0жество другHвъ и3 ласкaтелей: є3гдa же въ ѕлострадaніи, вси2 далeче tстоsтъ. Ґпcли, є3гдA хrт0съ t всёхъ почитaемь и3 чуди1мь бsше, вси2 въ слёдъ є3гw2 шeствоваху, є3гдa же ѕлостраждaше вси2 є3го2 њстaвльше, далeче бэжaша. Тёмже не надёйсz на бlгополучeніе и3 почитaніе человёческое, но на бGа всю2 надeжду и3 ўповaніе своE возлагaй: дeнь и3 н0щь къ немY є3ди1ному с®цемъ и3 ўм0мъ всегдA возвышaйсz.</verse>
	<verse number="з7">Предпочитaніе и3 слaва человёческа, за благополучeніемъ, ћкоже сёнь за с0лнцемъ шeствуетъ: є3гдA с0лнце сіsетъ, тогдA и3 сёнь њбрэтaетсz: є3гдa же и3зни1че, тогдA и3 сёнь погибaетъ. си1це и3 є3гдA є4сть комY благополучeніе, вси2 человёцы слaвzтъ и3 почитaютъ: є3гдa же лишeніе, вси2 презирaютъ и3 нерадsтъ њ нeмъ. Ўпод0бисz п0льному жeлтому цвёту и4же съ восхождeніемъ с0лнца t вост0ка развивaетсz, со захождeніемъ же пaки къ зaпаду согибaетсz, и3 никогдaже во є3ди1ной мёрэ стои1тъ: си1це и3 мjръ сeй со нрaвы и почитaньми свои1ми.</verse>
	<verse number="}">Предпочитaютъ ќбw мн0гажды, и3 слaвzтъ человёцы пред8 nчи1ма слaдостнэ, tшeдше же посeмъ клевeщутъ, и3 њглаг0луютъ г0рестнэ. Днeсь дHбраz глаг0лютъ, и3 ѓбіе ќтрw ѕл†z: пред8 nчи1ма си1це, за nчи1ма же и4накw. Нёсть постоsнно, но премённо почитaніе человёческо, ѕэлH же прелeстно и3 преврaтно. Е#ди1ни почитaютъ, друзjи же безчeстzтъ: є3ди1ни похвалsютъ, друзjи же хyлzтъ: є3ди1ни дHбраz вэщaютъ, друзjи же ѕл†z. нёсть м0щно пребhти неподви1жнw, въ рaвнэй мёрэ человёческіz слaвы же и3 почитaніz, но всегдA въ премёнэ.</verse>
	<verse number="f7">Мjръ сeй съ почитaньми свои1ми при1снw њбращaтеленъ ўстр0енъ є4сть, ћкоже к0ло °млинов0е°<footnote>°мёлничье°</footnote>: всегдA t горы2 ни1зу, и3 t ни1зу горЁ непрестaннw њбращaетсz: є3гдa же престaнетъ водA тещи2, тогдA и3 nно2 њстаeтъ прaздно. Мjръ сeй всегдA лицемёрствуетъ: вsщшаz бо t вётрwвъ и3 бyри премёна на высотЁ почитaніz стоsщымъ, нeже во ўд0ли смирeніz и3 презрёніz шeствующымъ. Е#3ли1кw бо вели1ко почитaніе, толи1кw вsщшаz боsзнь, є3ли1w кто2 развели1читсz почитaніемъ и3 слaвою, толи1кw посeмъ смири1тсz безчeстіемъ, и3ли2 здЁ t чlвBкъ, и3ли2 nнaмw t бэсHвъ. є3ли1кw, речE, развели1чисz и3 разсвирёпэ почитaніемъ и3 слaвою, толи1кw дади1те є4й р†нъ и3 безчeстіz <ref>Ґпокал. гл+а }i</ref>.</verse>
	<verse number="‹">Тёмже, по є3ли1ку почитaемь є3си2, по толи1ку и3 недост0йна себE твори2 почитaніz: да пребывaетъ въ души2 твоeй всегдaшнее смирeніе. Пaмzтствуй смeрть, ћкw не зри1тъ на сaны и3 почит†ніz, но всёхъ рaвнw сравнsетъ. Гдё бо днeсь слaвимый, богaтый и3 почитaемый; гдЁ кнsзи и3 госп0діе; гдЁ вітjи и3 премyдріи вёка сегw2; гдЁ си1льніи и3 хрaбріи и3 мyжественніи; гдЁ мн0гими странaми и3 землsми њбладaвшіи; мaлъ гр0бъ вмэсти2 и5хъ днeсь. ГдЁ прекрaсніи и3 благолёпіемъ лицA цвэтyщіи; tид0ша, ћкw никогдaже бhша: и3змэни1шасz, ни слёда почитaніz и3 слaвы њстaвиша.</verse>
</chapter>
