=== alvakim/spiritalph/xml/chapter.dtd
<!ELEMENT chapter (title, inscription, verse*)>
<!ATTLIST chapter
	part CDATA #REQUIRED
	chapt CDATA #REQUIRED
	verse_cnt CDATA #REQUIRED
>
<!ELEMENT title (#PCDATA)>
<!ELEMENT inscription (#PCDATA)>
<!ELEMENT verse (#PCDATA | ref | footnote)*>
<!ATTLIST verse
	number CDATA #REQUIRED
>
<!ELEMENT ref (#PCDATA)>
<!ELEMENT footnote (#PCDATA)>
<!--ELEMENT init (#PCDATA)-->
<!ELEMENT verses (title, subtitle, (inscription?, verse)*)>
<!ATTLIST verses
	nr CDATA #REQUIRED
	verse_cnt CDATA #REQUIRED
>
<!ELEMENT subtitle (#PCDATA)>

=== alvakim/spiritalph/xml/p11.xml
<?xml version="1.0" encoding="Windows-1251"?>
<!DOCTYPE chapter SYSTEM "chapter.dtd">
<?xml-stylesheet type="text/xsl" href="chapter.xsl" ?>
<chapter part="1" chapt="11" verse_cnt="10">
	<title>ГлавA пeрваz нaдесzть</title>
	<inscription>Њ є4же ћкw нёсть св0йственна чlвёку плотскaz п0хоть, но t преступлeніz ґдaмлz р0ду нaшему прибhвшаz.</inscription>
	<verse number="№">T тлёніz и3 грэхA рождeнъ бhвши, не къ тлёнію и3 грэхY пaки њбращaйсz, но t тлёніz къ нетлёнію  ўсeрднw восходи1ти тщи1сz, ћкw да прeжде џбщагw воскrніz ўмeршую грэх0мъ и страстьми2, безгрёшіемъ и3 безстрaстіемъ воскреси1ши дyшу, и3 t смeрти къ безсмeртію приведeши ю5. Не дрeвнzгw ґдaма престyпльшагw, но вторaгw хrтA безгрёшнагw жи1зни послёдуй: живyщіи бо по пл0ти по престyпльшемъ ґдaмэ, ўмрeти и4мутъ, хrтy же послёдующіи, ўмeршіи въ вёцэ сeмъ плотск0му мудровaнію, ктомY не ќзрzтъ смeрти г0рестныz, т0чію рaдостное њ гDэ t пл0ти преселeніе.</verse>
	<verse number="в7">Ґдaмъ, є3гдa бы прeбылъ въ св0йственномъ є3мY t гDа ўстроeніи, є3гдa бы прeбылъ при бз7э, люб0вію t тогw2 не tлучazсz. t негHже создaнъ бhсть, не бы2 подпaлъ смeрти и3 тлёнію. Но понeже њстaви творцA, къ твaри же прилэпи1сz: њстaви св0йственное, tню1дуже бытіE своE и3мЁ, прилэпи1сz же не къ св0йственному плотск0му неразyмному вожделёнію, тогw2 рaди по нyждэ подпадE тлёнію и3 смeрти: нетлёніz бо и3 жи1зни tлучи1всz, по нyждэ подпадE въ сицево2 плотск0е неразyмное сочетaніе, и3 t совершeнна рaзума и3 в0зраста, преступлeніемъ низведE є3стество2 нaше въ дётскій в0зрастъ и3 безсловeсное младоyміе, во є4же мaлыми нёмотсвующими nтрочaты въ мjръ сeй всeмъ раждaтисz нaмъ. Тh же nтрочaтемъ рождeнъ бhвый, не ктомY въ младоyміе впaдай, но въ совершeнъ, ћкоже в0зрастъ, си1це и рaзумъ возрастaй и3 преуспэвaй: сaмъ же возрaстши, и3нёхъ не въ безсловeсіе дётское, но въ совершeнъ возрастъ и3 рaзумъ благовэствовaніемъ роди1ти тщи1сz: да t тмы2 неразyміz къ свёту рaзума и3 познaніz приведeши всёхъ.</verse>
	<verse number="G">Не по преступлeніи несв0йственной плотск0й жи1зни прилэплsйсz, но прeжде преступлeніz t гDа безгрёшному ўстроeнію благоразyменъ подражaтель бyди. Е$же бо днeсь по пл0ти житіE, по преступлeніи т0е содёzсz, ґ є4же по дyху, прeжде преступлeніz, t гDа самагw2 сіE ўстроeніе бЁ. Тёмже не по претуплeніи, но прeжде преступлeніz дух0внэй њ гDэ послёдуй жи1зни, да прeжде смeрти, смeрти и3 тлёніz грэх0внагw свободи1шисz. Лyчше благоизв0льнw днeсь во врeменной жи1зни воскрeснути дyхомъ, и3 жи1ти всегдA гDви, нeже по г0рестной смeрти, съ неизвёстнымъ чazніемъ, чazти воскrніz и3 жи1зни. Лyчше днeсь њставлsти врeменное плотск0е сладострaстіе со њправдaніемъ и3 похвал0ю, нeже посeмъ со њсуждeніемъ и3 поношeніемъ сегw2 лишaтисz. Тёмже не повини1сz плотск0му неразyмному вожделёнію, но рaзумомъ плотскjz п0хwти востzзaй, да не ћкw младоyменъ дётищь посмэsнъ бyдеши.</verse>
	<verse number="д7">Ћкоже не t сочетaніz, и3 безсловeсныz плотскjz п0хоти ґдaмъ и3 є4vа и3спeрва сотворeни бhша, си1це и3 мы2 вси2 тaкw раждaтисz въ мjръ и3мёли бhхомъ: и3 ћкоже ґдaмъ, ѓбіе вси2 t небытіS въ бытіE приведeни бhли бhхомъ. Но понeже преступи2 ґдaмъ зaповэдь, и3 самоизв0льнw безсловeсію, и3 п0хотемъ плотски1мъ подпадE, тогw2 рaди по нyждэ си1це безсловeснw бhти, и3 раждaтисz въ мjръ, и3 мы2 њсуждeни є3смы2. Tтyду толи1кіz ск0рби и3 печaли, плaча же и3 рыдaніz и3сп0лнена жи1зни нaша: послэди1 же смeртію г0рькою тyю печатлёемъ. Хотs бо гDь и3звести2 честн0е t недост0йнагw, смeртнымъ пресэчeніемъ, t плотскaгw сплетeніz пресэкaему жи1знь нaшу бhти ўстр0и, да не вёчнующее пребyдетъ ѕл0е, но да возведeтъ нaсъ всёхъ вёрующихъ на лyчшее дрeвнее достоsніе и3 первоoбрaзіе: ѓще бо бы2 сіE бhло добро2 и3 совершeнно, не бы2 взhскивалъ бGъ t нaсъ лyчшихъ, не бы2 смeртію пресэцaлъ плотскyю жи1знь нaшу.</verse>
	<verse number="є7">T св0йственнагw св0йства, въ несв0йственное плотск0е хотёніе поп0лзшесz, смeрти и3 тлёнію подпад0хомъ. И#спeрва бо не въ смeрть, ни въ безсловeсное плотск0е похотёніе и3 сочетaніе t гDа создaни бhхомъ: но въ б9eственное желaніе и3 люб0вь. И$бо въ раи2 прeжде преступлeніz не бЁ п0хоти и3 плотскaгw вожделёніz, но по преступлeніи и3 по и3згнaніи и3з8 раS плотскaz п0хоть и3 вожделёніе бhсть, тaже посeмъ смeрть. Сегw2 рaди п0хоть плотскaz смeртію ўпражднsетсz, ўпраждненa же бhвши смeртію, не ктомY пaки во грzдyщей вёчной жи1зни слёдъ є3S њбрsщетсz, но б9eственнагw желaніz и3 любвE вси2 бGу ўгождaющіи во вёки вэкHвъ наслаждaтисz бyдутъ.</verse>
	<verse number="ѕ7">Раждaетсz человё4къ t жены2 пл0тски въ жив0тъ, и3 пaки безсловeснw соединszйсz є4й, њбумирaетъ t бGа душeю: ћкоже с0ль t воды2 раждaетсz, и3 пaки водЁ прикасazсz растоплsетсz и3 и3счезaетъ, си1це и3 въ сeмъ є4сть. Сегw2 рaди t плотскaгw грэх0внагw сочетaніz рождeнъ бhвши, не пaки ко грэх0вному плотск0му сплетeнію лэпи1сz, да не ћкw с0ль растaеши. Не бо2 на сіE t бGа сотворeнъ є3си2, да пaки на т†zжде грэхHвнаz плотскaz дBйства њбращaешисz и3 ўмирaеши, но да ко первоoбрaзному св0йству, и3 t гDа безгрёшному ўстроeнію восх0диши, и3 преуспэвaеши взыскyz лyчшихъ и3 бlжeннэйшихъ. Пріsтенъ ќбw є4сть по зак0ну днeсь по пл0ти брaкъ, но чистотA и3 цэломyдріе сугyбw сyть л{чша и3 пресл†внэйша, въ нsже и3спeрва t гDа ўстр0енъ бЁ ґдaмъ. брaкъ ќбw т0чію чист0тствовати, и3 в‰щашаz разумёти не хотsщымъ, и3ли2 не могyщымъ, днeсь на мaлое врeмz попущeнъ є4сть, чистотa же пребывaющаz є4сть во вёки вёчныz.</verse>
	<verse number="з7">КRщeніемъ во хrтA, вторhмъ д¦0внымъ порождeніемъ рождeнъ бhвши, t первор0днагw грэхA вод0ю и3 д¦омъ њмhлсz є3си2: не ктомY ќбw пaки грэх0мъ плотскjz п0хоти и3 дёйствіz плэни1сz: да не возвращaющемусz псY на своS блевHтины ўпод0бишисz. T тмы2 и3 безсловeсіz tврати1лсz є3си2, не пaки ко тмЁ и3 безсловeсію њбращaйсz, но къ свёту рaзума, и3 всёхъ вещeй познaніz провозрастaй, и3 присоединeнъ бывaй. БGомъ сотворeнъ є3си2, къ немY лэпи1сz. БGомъ создaнъ є3си2, къ немY люб0вію соединeнъ бyди. T негw2 бытіE своE и4маши, къ немY всeю душeю твоeю прилэплsйсz: чрез8 плотск0е бо грэх0вное вожделёніе и3 п0хоть содёzсz смeрть, и3 t бGа всеконeчное tчуждeніе: чрез8 сохранeніе же чистоты2 жив0тъ, и3 къ бGу совершeнное присвоeніе.</verse>
	<verse number="}">Рождeнное t пл0ти, пл0ть є4сть, и3 рождeнное t д¦а, д¦ъ є4сть <ref>Їwaн. за? }</ref>. Рождeнъ є3си2 д¦0внымъ рождeніемъ кRщeніz, пaки же вторhмъ д¦0внымъ рождeніемъ и4ночества роди1лсz є3си2 не ктомY ќбw плотск0му рождeнію грэх0вному, и3 сплетeнію тэлeсному ревнyй, и3ли2 зави1ди: но восходи2 на л{чшаz и3 пресл†внэйшаz. Ћкоже бGу њбэщaлсz є3си2, си1це д¦0внэ возрастaй и3 преуспэвaй: сaмъ д¦0внэ роди1вшисz, и3 и3нёхъ д¦0внw роди1ти тщи1сz, ґ не  плотск0ю слaстію плэнeнъ бyди. Плотск0е бо сочетaніе т0чію не могyщымъ, и3ли2 не хотsщымъ ўдержавaтисz, њстaвлено бhсть, не и3зволsющымъ же л{чшаz, х{ждшаz њставлsютсz. Е#гдA люб0вь б9eственнаz презирaетсz, тогдA плотск0е безсловeсное наступaетъ свzзaніе.</verse>
	<verse number="f7">Тёмже престaни плотскaгw дётскагw и3грaніz желaти самоизв0льнw, да не по сeмъ њставлsти бyдеши и3 нев0лею съ вsщшею своeю тsжестію. Да не прельщaетъ тS добр0та и3 красотA лицA тлённыz пл0ти: и3стлэвaетъ бо и3 и3змэнsетсz, и3 погибaетъ вск0рэ: нёсть ви1дэти состарёвшагосz бlголёпна: нёсть бо во гр0бэ красоты2 неистлёвшіz, нижE въ д0лго врeмz сі‰ пребыв†ющаz сyть. Всsка бо красотA плотскaz џгнь є4сть, всsко благолёпіе росA ќтреннzz, всsка пл0ть травA, всsка слaва человёческаz ћкw цвётъ сeльный: и4зше травA, и3 цвётъ є3S tпадE: глаг0лъ же гDнь т0чію є3ди1нъ, и3 бжcтвеннаz є3гw2 люб0вь пребывaетъ во вёки <ref>Їакw+ за? }</ref>.</verse>
	<verse number="‹">Призывaетъ ли тS ўzзвлsтисz красот0ю лицA и3стлёвшаz во гр0бэ пл0ть, њбhкшагw зрёти пристрaстнw зри6маz; но ќбw днeсь зри2 во гр0бэ сyщихъ прeжде тебE, тогдA посeмъ навhкнеши, ±же бyдутъ и3 по тебЁ, ћкw нёкто речE. Ничт0же бо и4но и3 по тебЁ бhти и4мать, т0чію є4же пред8 тоб0ю со и3нёми сбhстсz: ґ є4же со и3нёми сбhстсz, сіE и3 съ тоб0ю всsкw неизмённw сбyдетсz. Сегw2 рaди не прилагaй сeрдца своегw2 къ твaри, но всe желaніе своE и3 люб0вь возводи2 ко вс‰ сотв0ршему, tню1дуже бытіE своE и4маши и3дёже ти2 є3стeственнэ св0йственно є4сть: и4бо нигдёже и4ндэ, во всёхъ си1хъ њбрsщеши вёчный жив0тъ, и3 непрел0жну души2 своeй тишинY, т0чію въ гDэ бз7э, и3 въ прес™0й є3гw2 любви2, и3 въ блгdти прес™aгw и3 животворsщагw д¦а.</verse>
</chapter>

=== alvakim/spiritalph/xml/p13.xml
<?xml version="1.0" encoding="Windows-1251"?>
<!DOCTYPE chapter SYSTEM "chapter.dtd">
<?xml-stylesheet type="text/xsl" href="chapter.xsl" ?>
<chapter part="2" chapt="1" verse_cnt="10">
	<title>ГлавA пeрваz</title>
	<inscription>Њ є4же блюсти1сz во всёхъ вeщехъ сyетнагw велехвалeніz.</inscription>
	<verse number="№">Похвали2 їеrли1ме гDа, хвали2 бGа твоего2 сіHне <ref>Pал0мъ рм7з</ref>, глаг0летъ прbр0къ. Никт0же дост0инъ похвалsемь и3 прославлsемь во всeмъ бhти и4мать, т0чію є3ди1нъ бGъ вс‰ сотвори1вый, и4мже вс‰ бhша. Хвали1те (речE) гDа вси2 kзhцы, похвали1те є3го2 вси2 лю1діе <ref>Pал0мъ рѕ7i</ref>. Хвaльно и3 прослaвлено и4мать бhти и4мz гDне во вёки. и3 пaки: да не хвaлитсz премyдрый въ мyдрости своeй, ни богaтый въ богaтствэ своeмъ: но њ сeмъ да хвaлитсz, хвалsйсz, є4же разумёти и3 знaти гDа, и3 твори1ти сyдъ и3 прaвду посредЁ земли2 <ref>№ Цаr: гл+а в7</ref>.</verse>
	<verse number="в7">Во всёхъ вeщехъ не похвалsйсz сaмъ, ни t и3нhхъ похвалы2 и3щи2, нижE похвалsємымъ t когw2 зави1ди, да не сугyбую тщетY во nбои1хъ пріи1меши, разсhпаніе и3справлeній, и3 њсуждeніе зaвисти. Не хвалsй бо себE, но є3г0же бGъ похвaлитъ, т0й во всeмъ є4сть и3скyсенъ: хвалsйсz бо, речE, њ гDэ да хвaлитсz <ref>в7 Корjн. за? Rч</ref>: прославлszйсz, њ гDэ да прославлsетсz, є3гHже вс‰ сyть. Не t человBкъ въ чес0мъ велехвали1мый, ўтэшeніz t похвaлъ и3щи2: но въ бз7э вс‰ даровaвшемъ и4стиннw взыскyй: человёчєска бо врeмєнна и3 непосто‰нна, б9іz же вBчна и3 непрелHжна. Тщи1сz ты2 њ слaвэ б9іей, ћкw да и3 бGъ прослaвитъ тS. Ѓще бо њ слaвэ б9іей пещи1сz бyдеши, сaмъ тщеслaвитисz не восх0щеши, и3 бGъ самaго прослaвитъ тS: ѓще же ты2 бGа презрёвъ, њ свои1хъ си2 пещи1сz бyдеши, бGъ њстaвитъ тS.</verse>
	<verse number="G">Не похвалsйсz сaмъ, нижE похвалsющихъ тS въ слaдость пріeмли, да не восплащeніе свои1хъ бл†гъ похвалeніемъ человёческимъ здЁ воспріи1меши: бlжaщіи бо вaсъ лстsтъ вы2, и3 стєзи2 н0гъ вaшихъ возмущaютъ, гlетъ прbр0къ <ref>И#сaіи гл+а G</ref>. T похвалh бо роди1тсz самолю1біе, t самолю1біz же гордhнz и3 дмeніе, тaже и3 t бGа tчуждeніе. Лyчше не содёлати что2 преслaвно въ мjрэ, нeже содёлавши безмёрнw велехвали1тисz. Фарісeй бо пресл†внаz содёлавъ, велехвалsйсz возношeніемъ, поги1бе: мытaрь же ничт0же блaго содёлавъ, смирeніемъ спасeсz. Џвому во благи1хъ є3гw2 t похвалы2 р0въ бhсть: џвому же смирeніz рaди t р0ва возведeніе. глаг0летъ бо: ћкw сни1де сeй њправдaнъ въ д0мъ св0й пaче џнагw <ref>Луки2 за? п7f</ref>. Похвали1сz дв7дъ и3считaніемъ мн0жества людeй, и3 смeртную кaзнь въ лю1дехъ под8sтъ. Е#зекjа мн0жествомъ богaтства пред8 послы2 вавmлHнскими похвали1сz, всегw2 сокр0вища своегw2 пострадA. Посeмъ навуходон0соръ созидaніемъ вавmлHна похвали1сz, со скоты2 ћкw ск0тъ сeдмь лётъ травY kдE.</verse>
	<verse number="д7">Ѓще что2 твори1ши блaго, блюди1сz велехвалeніz: ѓще же похвaлишисz, вс‰, ±же и3справлeніемъ стzжaлъ є3си2, велехвалeніемъ напрaснw погуби1ши, и3 блгdти б9іz tтщети1шисz: t похвалh бо возношeніе, t возношeніz же падeніе, падeніемъ же, t бGа tлучeніе. БGъ вс‰ сотвори1вый, не тaкw t человBкъ, ћкw подобaетъ, и3 прославлsемь и3 величaемь є4сть: тh же ничт0же t себE и3мёzй, безсловeснw t всёхъ похвалsемь и3 прославлsемь бhти х0щеши. Не желaй ќбw себЁ похвалы2 t чlвBкъ, нижE похвалsйсz сaмъ, ўвёсть бо бGъ, ўвёдzтъ и3 чlвёцы, ѓще дэлA твоS бл†га бyдутъ, и3 кромЁ твоегw2 велехвалeніz похвaлzтъ тS. Ѓще бо сaмъ велехвали1тисz бyдеши, вси2 презрsтъ тS: ѓще же ты2 сaмъ велехвали1тисz не бyдеши, бGъ и3 вси2 человёцы похвaлzтъ тS. ѓще њ себЁ ўмолчи1ши, бGъ возгlетъ њ тебЁ: ѓще же сaмъ њ себЁ велерёчити бyдеши. бGъ ўм0лкнетъ њ тебЁ, и3 tвeржетъ тS.</verse>
	<verse number="є7">Не бyди ћкоже к0кошь, њ к0емлибо и3справлeніи велехвалsщисz, да не п0мощи б9іz tтщети1шисz.  к0кошь бо њ и3знесeніи своегw2 kицA, ѓбіе пред8 всёми возглашaетъ, и3 велехвалsсz кдaчетъ, ћкw и3знесE kицE: тh же не бyди тaкw безyменъ, нижE пред8 всёми и3з8zвлsй своS и3справлє1ніz, да не здЁ себЁ восплащeніе t человBкъ воспріи1меши: но молчaніемъ покрывaй своS и3справлє1ніz, да t бGа є3ди1нагw ўвBдана и3 похвалє1на бyдутъ. Ѓще бо ты2 сaмъ похвалsешисz, t бGа похвалeнъ не бyдеши. ѓще тh сaмъ велехвaлишисz, никт0же t человBкъ похвaлитъ тS: ѓще ли ни2, вси2 ўблажaтъ тS. nбaче лyчше ти2 є4сть, да їнjи похвaлzтъ тS, нeже ты2 сaмъ безсловeснw похвaлишисz. Не хвали1сz во ќтренихъ, не вёси бо что2 роди1тъ находsй [дeнь:] да хвaлитъ тS и4скренній тв0й, ґ не твоS ўстA, глаг0летъ соломHнъ <ref>При1тчей к7з</ref>.</verse>
	<verse number="ѕ7">Дёйство є4сть вeліе твоегw2 неразyміz, ћкw своS безчи1слєннаz ѕл†z ни є3ди1ному t человBкъ tкрhти и3 kви1ти и3зволsеши: ѓще же бyдетъ и3 мaло что2 благ0е, всBмъ рaдостнw tкрывaеши, всBмъ желaтельнw ћви1ти, и3 t всёхъ похвалsемь и3 прославлsемь бhти х0щеши, ћкw да t всёхъ г0рдостнагw тщеслaвіz наслади1шисz. Почто2 ќбw ты2 трeбуеши ўтэшeніz t похвaлъ человёческихъ; Дов0льно ти2 є4сть на сeмъ, ѓще дэлA твоS t бGа є3ди1нагw вёдwма и3 благопрі‰тна бyдутъ. Тёмже не похвалsйсz сaмъ, но t гDа є3ди1нагw похвалы2 њжидaй: не похвалszй бо себE ни въ чeмже, во всeмъ є4сть премyдръ: безсловeснw же въ чeмъ велехвалsйсz: во всeмъ є4сть безyменъ. безсловeсенъ є4сть сeй и3 неразyменъ ѕэлw2, и4же чуждeю, ґ не своeю ри1зою похвалsетсz, и3ли2 въ чуждeмъ богaтствэ, ґ не во своeмъ полагaетъ своE ўповaніе, си1це и3 въ тебЁ сіE.</verse>
	<verse number="з7">И#нjи мн0жество и3спрaвиша добродётелей: расточи1ша и3мBніz, њстaвиша бог†тства, содёzша пресл†внаz, просвэти1ша мjръ, ўмудри1ша чlвёки, мн0гихъ дyшы спас0ша, и3 не похвалsхусz: тh же ни мaло что2 блaго сотв0рь, нижE мaло что2 благоуг0дно содёzвъ, њ ничес0мже безсловeснw велехвaлишисz. Не похвалsйсz ќбw ты2 сaмъ, но ѓще бGъ похвaлитъ тS, семY внемли2. ѓще бо что2 бyдетъ блaго, и3 кромЁ твоегw2 велехвалeніz бGъ ўвёсть: ѓще є3мY є4сть ўг0дно, и3 не хотsщу ти2 прослaвитъ тS: прослaвитъ ќбw џнъ, и3 не прeзритъ ни є3ди1нагw без8 вeліzгw возмeздіz. Ѓще бо ты2 сaмъ похвалsтисz бyдеши, рaзума лиши1шисz, и3 t бGа похвалeнъ не бyдеши.</verse>
	<verse number="}">Не похвалsйсz ни въ чeмже, нижE глаг0ли, ћкw богaтъ є4смь, и3 всёми благи1ми њбогати1хсz, и3 ничт0же трeбую, но не вёси, ћкw тh є3си nкаsненъ, ни1щъ, и3 мнjй, и3 слёпъ, и3 нaгъ, глаг0летъ т†инъ ви1децъ <ref>Ґпокал. гл+а G</ref>. Сегw2 рaди, є3гдA и3 вс‰ сотворитE повелBннаz вaмъ, гlите: ћкw раби2 непротрeбни є3смы2, є4же д0лжни бёхомъ сотвори1ти, сотвори1хомъ, гlетъ гDь <ref>Луки2 за? п7д</ref>. Всsка бо прaвда человёческаz пред8 гDемъ, ћкw рyбъ повeрженный є4сть на гн0ищи, гlетъ прbр0къ <ref>И#сaіи гл+а з7</ref>. Вёмъ бо ћкw ни ты2 чlвBкъ велехвалsщихсz лю1биши, є3гдA кто2 пред8 тоб0ю величazйсz похвалsетсz: си1це нижE бGъ: тh же ничт0же t себE и3мёzй, соплетaz себЁ похвалY пред8 и3нёми, и3 вс‰ себЁ причитaz велехвaлишисz. Но не нaмъ, гDи, не нaмъ, но и4мени твоемY дaждь слaву, глаг0летъ прbр0къ <ref>Pал0мъ рGi</ref>. Хвали1сz ты2 њ бз7э, и3 бGъ восхвaлитсz њ тебЁ: возлюби2 ты2 бGа, и3 бGъ возлю1битъ тебE: ѓще ты2, сво‰ си взыскyz, прeзриши бGа, и3 бGъ прeзритъ тS, и3 tри1нетъ тS.</verse>
	<verse number="f7">Что2 хвaлишисz во ѕл0бэ си1льне, глаг0летъ прbр0къ <ref>Pал0мъ н7а</ref>; Почто2 трeбуеши t и3нhхъ во бlги1хъ похвалы2; и3 сaмъ бо ты2 вёси, ћкw блaго є4сть. бlг0е бо благи1мъ є4сть всегдA, ѓще и3 ни t є3ди1нагw є4сть похвалsемо: ѕл0е же ѕлhмъ, ѓще и3 ни t є3ди1нагw є4сть хyлимо. Ѓще тебE и3 вси2 человёцы похвалsютъ, чт0 ти t сегw2 прибyдетъ: ѓще ни є3ди1нъ, въ чeмъ tтщети1шисz; ѓще и3 ни t є3ди1нагw во благ0мъ похвалeнъ бhлъ бы є3си2, t бGа же самaгw є3гдA похвалeнъ бyдеши, довлёетъ ти2. T человBкъ хвали1му бhти ничт0же є4сть: не бо2 человBкъ рaди и4маши что2 твори1ти благ0е, но бGа рaди. Сегw2 рaди не t человBкъ, но t бGа є3ди1нагw похвалы2 и3 возвышeніz и3щи2, да во вёки t негw2 похвалeнъ и3 прослaвленъ бyдеши, и3 возмeздіе вёчное t негw2 пріи1меши.</verse>
	<verse number="‹">Тёмже во благополyчіи и3 почитaніи, не ѕэлw2 велехвали1сz, въ презрёніи же въ развращeніе и3 въ нечazніе не впaдай, но во nбои1хъ мёренъ и3 благоразyменъ пребyди. Е#гдa ти є4сть что2 блaго и3 рaдостно, не безсловeснэ похвалszсz весели1сz: є3гдa же что2 ѕло2 приключи1тсz, не безпaмzтнw ск0рбію себE снэдaй. Вёкъ бо сeй настоsщій ўд0бь премэни1теленъ є4сть, и3 вс‰ вє1щи въ нeмъ преврaтны: но бGу њ всёхъ вeщехъ славосл0віе и3 бlгодарeніе приноси2, и3 є3мY вс‰ причитaй, да и3 џнъ тебЁ вс‰ сво‰ привмэни1тъ, и3 вёчный жив0тъ подaстъ.</verse>
</chapter>

=== alvakim/spiritalph/xml/p1.xml
<?xml version="1.0" encoding="Windows-1251"?>
<!DOCTYPE chapter SYSTEM "chapter.dtd">
<?xml-stylesheet type="text/xsl" href="chapter.xsl" ?>
<chapter part="1" chapt="1" verse_cnt="10">
	<title>ГлавA пeрваz</title>
	<inscription>Њ є4же пeрвэйшаz винA бhсть ґдaмлю падeнію, неразyміе, и3 всеконeчное себE непознaніе.</inscription>
	<verse number="№">Мн0зи мнHгіz и3 разли6чныz предлагaютъ ґдaмлю падeнію вины6: є3ди1ны безвёріе, друзjи преслушaніе, трeтіи же гордhню, и3 славолю1біе, и3нjи же и4ны разли1чныz вины6: мh же ни є3ди1ну t си1хъ пeрвэйшую бhти мни1мъ, т0чію безyміе и3 всёхъ вещeй неразсмотрeніе. <ref>Кни1га nбёдъ сл+о в7 на нLю к7ѕ</ref></verse>
	<verse number="в7">Пeрвэйшаz ґдaму въ раи2 бhсть зaповэдь, є4же дёлати, и3 храни1ти, си1рэчь дёлати рaзумомъ, є4же разумёти д0брэ, и3 храни1ти зпаовёданіе, є4же не преступaти. Но понeже не дёлаше рaзумомъ, сегw2 рaди не сохрани2 заповёданіz: t недёланіz бо ќмнагw, пeрвэе возрастE въ ґдaмэ невёріе, во є4же не вёровати бGу, и4же речE и3 заповёда: посeмъ t невёріz преслушaніе и3 преступлeніе, t преступлeніz же tпадeніе гDни блгdти, и3 б9eственныz є3гw2 любвE tчуждeніе.</verse>
	<verse number="G">Ѓще бы разумёлъ ґдaмъ бlгодaтелz, и3 предразсуди1лъ себЁ заповёданіе, не бы2 не невёровалъ заповёданію: ѓще бы вёровалъ, не бы2 преслyшалъ, не бы2 вкушaлъ заповёданнагw дрeва, не бы2 и3згнaнъ бhлъ и3з8 раS, не бы2 подпaлъ смeрти и3 тлёнію, не бы2 бGъ толи1кw њ нaсъ чудодёйствовалъ дот0лэ, донeлэ приведE нaсъ въ дрeвній рaзумъ, и3 всёхъ вещeй познaніе.</verse>
	<verse number="д7">Ћкоже не и3н0ю вин0ю tпадE ґдaмъ t бGа и3 є3гw2 бlгодaти, т0чію безyміемъ: си1це не и3нёмъ чи1мъ пaки кто2 присоедини1тсz є3мY, т0чію рaзумомъ, и3 всёхъ вещeй познaніемъ. Познaвый бо кто2 и4стиннw себE, познA бGа, и3 познaвый бGа , познA себE: съ бGомъ соединeнъ є4сть, и3 почи1въ t всёхъ дёлъ и3 трудHвъ свои1хъ, вни1де во с™и1лище б9іе, и3 прин0ситъ бGу всегдA ќмную д¦а слyжбу.</verse>
	<verse number="є7">Nбaче никт0же м0жетъ познaти бGа, донeлэ не познaетъ пeрвэе себE, не познaетъ же совершeннэ себE, донeлэ не пріи1детъ пeрвэе въ познaніе твaри, и3 всёхъ вещeй въ мjрэ зри1мыхъ, и3 разумэвaемыхъ разсмотрeніе. Е#гдa же пріи1де въ познaніе си1хъ, тогдA возм0жетъ пріити2 и3 въ познaніе себE, тaже и3 бGа, и3 тaкw прих0дитъ въ совершeнное съ бGомъ люб0вію соединeніе.</verse>
	<verse number="ѕ7">Тёмже, ѓще кто2 и4стиннw х0щетъ познaти гDа, познaти себE, и3 съ ни1мъ люб0вію соедини1тисz: да познaетъ пeрвэе всю2 твaрь, ви1димую и3 разумэвaемую, да ўвёсть всёхъ вещeй, и3 всеS твaри разсмотрeніе, t когw2, и3 чесw2 рaди сі‰ сyть, во є4же ни є3ди1ной вeщи ўтаeннэй и3 недоумённэй бhти t негw2, тaже себE, и3 всE є4же њ себЁ тaинство, тaже бGа, и3 всS є3гw2 неизречє1ннаz благодэ‰ніz, и3 тaкw прих0дитъ въ совершeнное всегw2 познaніе: и4бо подобаeтъ дHлнzz вс‰ разумёти, тaже гHрнzz: не бо2 t г0рнихъ на ни6жнzz восходи1ти д0лжни є3смы2: но t д0лнихъ на вы6шнzz. ТогH бо рaди всю2 твaрь, и3 всE мірск0е ўстроeніе, ћкоже нёкое ўчи1лище, и3ли2 зерцaло, пред8 џчи нaши бGъ положи2, ћкw да ўчaщесz, t д0лнихъ восх0димъ на вы6шнzz: ѓще же д0лнихъ не познавaемъ, то2 кaкw гHрнzz разумёти и4мамы;</verse>
	<verse number="з7">T рaзума и3 познaніz раждaетсz вёра, t вёры же зaповэдей б9іихъ хранeніе, t хранeніz же зaповэдей б9іихъ ўповaніе на бGа, t ўповaніz же на бGа б9eственнаz люб0въ: сeй же ўмн0женнэй бhвшей, совершeнное бывaетъ съ бGомъ соединeніе, и3 и3сполнeніе зак0на и3 прbр0кwвъ.</verse>
	<verse number="}">По є3ли1ку процвэтaетъ рaзумъ, по толи1ку возрастaетъ и3 вёра: и3 по є3ли1ку возрастaетъ вёра, по толи1ку ўмножaютсz добродётєли, по толи1ку раждaетсz и3 ўповaніе на бGа: и3 по є3ли1ку кто2 ўповaетъ, по толи1ку и3 бGа лю1битъ, и3 по є3ли1ку лю1битъ, по толи1ку и3 съ бGомъ соединsетсz, наслаждaющисz бжcтвенныz є3гw2 слaвы.</verse>
	<verse number="f7">T безyміz раждaетсz невёріе, t невёріz же преслушaніе, t преслушaніz же всsкъ грёхъ и3 преступлeніе. Кaкw кто2 м0жетъ вёровати, ничт0же разумёzй; не вёруzй же, нижE разумёzй ничт0же, кaкw м0жетъ сохранsти гDни зaпwвэди; не сохранszй же гDни зaпwвэди, кaкw м0жетъ и3мёти на бGа ўповaніе и3 люб0вь; Никaкоже.</verse>
	<verse number="‹">Тёмже прeжде всегw2, подобaетъ ўчи1тисz, не т0чію внёшнему трудY, но и3 дёланію ќмному, рaзуму, и3 всёхъ вещeй познaнію, ўд0бнэ всемY вёру є4млетъ, сохранsетъ всS гDни зaпwвэди, ўповaетъ на бGа, лю1битъ є3го2 всёмъ с®цемъ свои1мъ, и3 соединsетсz съ ни1мъ во є3ди1но, во є4же бhти є3мY всемY въ бз7э, и3 бGу въ нeмъ. Сицевhй прeжде воскrніz, воскресeніе души2 пріeмлетъ, и3 прeжде жи1зни, жи1знь вёчную наслёдуетъ, во є4же пожeртой бhти безсловeсіz смeрти, рaзума и3 познaніz жи1знію: сe бо, речE, є4сть жив0тъ вёчный, да познaемъ гDа, сe же и3 смeрть, не разумёти њ нeмъ.</verse>
</chapter>

=== alvakim/spiritalph/xml/p34.xml
<?xml version="1.0" encoding="Windows-1251"?>
<!-- edited with XML Spy v3.5 NT (http://www.xmlspy.com) by alakim (mai) -->
<!DOCTYPE verses SYSTEM "chapter.dtd">
<?xml-stylesheet type="text/xsl" href="chapter.xsl" ?>
<verses nr="1" verse_cnt="10">
	<title>СтіхослоHвіz пє1рваz,</title>
	<subtitle>любeзнагw къ бGу взывaніz.</subtitle>
	<verse number="№">Возлюблю1 тz, гDи, крёпосте моS: гDь ўтверждeніе моE, и3 прибёжище моE, и3 и3збaвитель м0й, бGъ м0й, пом0щникъ м01й, и3 ўповaю на него2: защи1титель м0й, и3 р0гъ спасeніz моегw2, и3 застyпникъ мо2й. ХвалS призовY гDа, и3 t вр†гъ мои1хъ спасyсz <ref>Pал0мъ з7i</ref>.</verse>
	<verse number="в7">К0ль возлю1блєнна селє1ніz твоS, гDи си1лъ; Желaетъ и скончавaетсz душA моS во дворы2 гDни: с®це моE и3 пл0ть моS возрaдовасz њ бз7э жи1вэ <ref>Pал0мъ п7г</ref>. Бlжeни живyщіи въ домY твоeмъ: въ вёки вэкHвъ восхвaлzтъ тS. Лyчше дeнь є3ди1нъ во дв0рэхъ твои1хъ, гDи, пaче тhсzщъ: и3зв0лихъ приметaтисz въ домY бGа моегw2 пaче, нeже жи1ти ми2 въ селeніихъ грёшничихъ <ref>Pал0мъ п7г</ref>.</verse>
	<verse number="G">К0ль возлюби1хъ зак0нъ тв0й, гDи; вeсь дeнь поучeніе моE є4сть. К0ль сладкA гортaни моемY словесA твоS, пaче мeда ўстHмъ мои1мъ; сегw2 рaди возненави1дэхъ всsкъ пyть непрaвды. Свэти1льникъ ногaма мои1ма зак0нъ тв0й, и3 свётъ стезsмъ мои1мъ. Њправд†ніz твоS вожделённа сyть, гDи, пaче злaта и3 кaмене чeстна мн0га, и3 слaждша пaче мeда и3 с0та <ref>Pал0мъ р}i</ref>.</verse>
	<verse number="д7">К0ль блaгъ бGъ Ї}левъ, пр†вымъ сeрдцемъ <ref>Pал0мъ o7в</ref>; К0ль мн0гое мн0жество блaгости твоеS гDи, ю4же скрhлъ є3си2 боsщымсz тебE; содёлалъ є3си2 ўповaющымъ на тS пред8 сhны чlвёческими; Скрhеши и5хъ въ тaйнэ лицA твоегw2 t мzтeжа человёческа <ref>Pал0мъ l</ref>. Nбaче бGови повини1сz, душE моS, ћкw t тогw2 терпёніе моE: и1бо т0й бGъ м0й и3 сп7съ м0й, застyпникъ м0й: не подви1жусz во вёкъ <ref>Pал0мъ …а</ref>.</verse>
	<verse number="є7">Њ бз7э спасeніе моE, и3 слaва моS. БGъ п0мощи моеS, и3 ўповaніе моE на бGа. Ўповaйте на него2 вeсь с0нмъ людeй: и3зліsйте пред8 ни1мъ сердцA вaша: ћкw бGъ пом0щникъ нaшъ є4сть. Не ўповaйте на непрaвду, и3 на восхищeніе не желaйте: богaтство ѓще течeтъ, не прилагaйте сeрдца. Е#ди1ною гlа бGъ, дв0z сі‰ слhшахъ, занE держaва б9іz, и3 твоS, гDи, млcть: ћкw ты2 воздaси комyждо по дэлHмъ є3гw2 <ref>Pал0мъ …а</ref>.</verse>
	<verse number="ѕ7">Б9е, б9е м0й, къ тебэ ќтренюю: возжадA тебE душA моS, к0ль мн0жицею тебЁ пл0ть моS, въ земли2 пyстэ и3 непрох0днэ и3 безв0днэ: тaкw во с™ёмъ kви1хсz тебЁ, ви1дэти си1лу твою2 и3 слaву твою2. Ћкw лyчши ми1лость твоS па паче живHтъ: ўстнЁ мои2 похвали1тэ тS, тaкw благословлю2 тz въ животЁ моeмъ: њ и4мени твоeмъ воздэжY рyцэ мои2. ПрильпE душA моS по тебЁ, менe же пріsтъ десни1ца твоS <ref>Pал0мъ …в</ref>.</verse>
	<verse number="з7">И$мже џбразомъ желaетъ є3лeнь на и3ст0чники воднhz, си1це желaетъ душA моS къ тебЁ, б9е. ВозжадA душA моS къ бGу крёпкому жив0му: когдA пріидY и3 kвлю1сz лицY б9ію; мlтва бGу животA моегw2. РекY бGу: застyпникъ м0й є3си2, почт0 мz забhлъ є3си2; и3 вскyю сётуz хождY, внегдA њскорблsетъ врaгъ <ref>Pал0мъ м7а</ref>;</verse>
	<verse number="}">ГDь просвэщeніе моE и3 сп7си1тель м0й, когw2 ўбою1сz; гDь защи1титель животA моегw2, t когw2 ўстрашyсz; Е#ди1но проси1хъ t гDа, то2 взыщY: є4же жи1ти ми2 въ домY гDни всS дни2 животA моегw2, зрёти ми2 красотY гDню, и3 посэщaти хрaмъ с™hй є3гw2. ВзыскA тебE лицE моE, лицA твоегw2 гDи взышY <ref>Pал0мъ к7ѕ</ref>.</verse>
	<verse number="f7">Гот0во с®це моE, б9е, гот0во с®це моE: воспою2 и3 пою2 во слaвэ моeй. Востaни слaва моS, востaни pалти1рю и3 гyсли, востaну рaнw. И#сповёмсz тебЁ въ лю1дехъ гDи, пою2 тебЁ во kзhцэхъ. Ћкw вeліz верхY нб7съ ми1лость твоS, и3 до џблакъ и4стина твоS. Вознеси1сz на нб7сA, б9е, и3 по всeй земли2 слaва твоS <ref>Pал0мъ Rз</ref>.</verse>
	<verse number="‹">Ты2 є3си2 б9е, держaва моS, разжзи2 ўтрHбы моS и3 сeрдце моE. Ћкw ми1лость твоS пред8 nчи1ма мои1ма є4сть <ref>Pал0мъ к7є</ref>. Посли2 свётъ тв0й и3 и4стину твою2, тa мz настaвиста, и3 введ0ста мS въ г0ру с™yю твою2, и3 въ селє1ніz твоS. И# вни1ду къ жeртвеннику б9ію, къ бGу веселsщему ю4ность мою2: и3сповёмсz тебЁ въ гyслехъ б9е, б9е м0й. Вскyю приск0рбна є3си2 душE моS; и3 вскyю смущaеши мS; ўповaй на бGа, ћкw и3сповёмсz є3мY, спасeніе лицA моегw2, и3 бGъ м0й <ref>Pал0мъ м7в</ref>.</verse>
</verses>

=== alvakim/spiritalph/xml/p9.xml
<?xml version="1.0" encoding="Windows-1251"?>
<!DOCTYPE chapter SYSTEM "chapter.dtd">
<?xml-stylesheet type="text/xsl" href="chapter.xsl" ?>
<chapter part="1" chapt="9" verse_cnt="10">
	<title>ГлавA девsтаz</title>
	<inscription>Њ є4же не ўzзвлsтисz ли1цами, и3 не порабощaтисz п0хотію плотск0ю.</inscription>
	<verse number="№">Не ўzзвлsйсz сeрдцемъ въ красотЁ лицA тлённыz пл0ти: травA и3 цвётъ є3z tпадE: Бжcтвеннаz же т0чію люб0вь пребывaетъ во вёки. Не зри1мыми красотaми ўzзвлsй своE сeрдце, но къ зри1мыхъ и3 незри1мыхъ содётелю ќмъ и3 дyшу свою2 возводи2.</verse>
	<verse number="в7">Воззрёніz съ вожделёніемъ не красотY чуждyю, и3 безстyднагw прикосновeніz, лобзaніz же и3 њсzзaніz, ћкw смертон0сна ћда бёгай, да не въ блубинY грэх0вную поги1бели впадeши, и3 въ сBти діaволи њстaнеши: преткнyвсz же въ сeмъ , кромЁ ск0рби и3 тsжести никогдaже пребyдеши.</verse>
	<verse number="G">Не любодёйствуй въ с®цэ твоeмъ съ твaрію, да не прогнёваеши гDа сотв0ршаго ю5: ѕэлH бо вмaлэ твaрь и3 плотскaz слaсть прин0ситъ ўтэшeніе, пот0мже ѓбіе нав0дитъ мeрзость и3 тsжесть душЁ. Мaлое приwбрётеніе, вели1ка же тщетA: мaлое весeліе, вели1ка же ск0рбь: нёсть t си1хъ толи1кw ўтэшeніz, є3ли1кw по си1хъ тsжести и3 г0рести.</verse>
	<verse number="д7">Не прельщaйсz лёпотою, и3 постaвою и3 прекрaснымъ лицeмъ: ўд0бь бо сокрушaемо и3 и3счезновeнно є4сть. Пaмzтствуй по премэнeніи крас0тномъ гн0й, и3 по њбуревaніи п0хотномъ бывaющыz скHрби и3 т‰жести: то2 никогдaже прельсти1шисz, нижE к0ею красот0ю пл0ти, и3 п0хотію грэх0вною ћтъ бyдеши.</verse>
	<verse number="є7">Вёдаz  бyди, ћкw въ мaлэ врeмени слaдокъ є4сть грёхъ, въ д0лго же врeмz є4сть г0рекъ: вмaлэ ўтёшенъ, над0лзэ же ск0рбенъ: вмaлэ  рaдостенъ, над0лзэ же плачeвенъ, и3 при разлучeніи t тёла, ѕэлw2 тsжестенъ є4сть, и3 многопечaленъ душЁ.</verse>
	<verse number="ѕ7">Ѓще не и3скуси1лъ є3си2 грэхA, и3скушaти є3гw2 вeщію не хощи2, да не ќдицу смeртную въ г0рести є3гw2 снёси: и3 не и3скушaющи бо є3гw2 вёси, ћкw мeрзостенъ є4сть, и3 по нeмъ горькA болёзнь, и3 вкуси1вши є3гw2, нёсть м0щно и3збhти ск0рби и3 печaли.</verse>
	<verse number="з7">Не пріeмли въ слaсть врeменныz слaсти: всsка бо врeменнаz слaсть не пребывaющаz вёчнw, сyетна є4сть: всsкое ўтэшeніе плотск0е и3счезновeнно є4сть: всsкое наслаждeніе врeменное ћвственнаz прeлесть и3 тsжесть душЁ. П0хоть плотскaz смeрть є4сть душE: бжcтвенное же желaніе и3 люб0вь, жив0тъ є4сть, и3 присносyщнаz рaдость.</verse>
	<verse number="}">Пaмzтствуй, слaсть врeменную и3 красотY плотскyю бhти гн0й, и3 въ тлёніе њбращeніе, и3 никогдaже настоsщымъ безсловeснw пригвозди1шисz. Плотск0ю люб0вію не ўводи1сz, нижE ўтэшeніе своE въ нeй полагaй: прелeстна бо є4сть, л0жна и3 лицемёрна, никогдaже во є3ди1ной мёрэ стоsщаz, нижE во вёки пребывaющаz.</verse>
	<verse number="f7">Не прилэплsйсz тaмw, и3дёже нёсть вёчно: нижE ўтэшeніz и3щи2, и3дёже є4сть преврaтно: мн0зи бо безсловeснw ўzзви1вшесz красот0ю лицA, и3 п0хотію плотск0ю прельсти1вшесz, мн0гъ соблaзнъ и3 претыкaніе мнHгимъ состaвльше, жи1знь свою2 ѕлЁ скончaша, и3 бёсу бhша подр{чницы: и3 маловрeменныz рaди слaдости, жи1зни вёчныz tтщети1шасz.</verse>
	<verse number="‹">БGу є3ди1ному бyди порабощeнъ и3 тогw2 добр0тою, и3 бжcтвенною люб0вію ўsзвлено сeрдце своE и3мёй, и3 не прельсти1шисz во вёки, но пaче всёхъ прeлестей превhшше бyдеши, въ ми1рэ и3 пок0и всегдaшнемъ њбрzщешисz: пріи1меши же и3 получи1ши бlгyю чaсть, ћже не tи1метсz t тебE во вёки.</verse>
</chapter>
