=== alvakim/spiritalph/xml/chapter.dtd
<!ELEMENT chapter (title, inscription, verse*)>
<!ATTLIST chapter
	part CDATA #REQUIRED
	chapt CDATA #REQUIRED
	verse_cnt CDATA #REQUIRED
>
<!ELEMENT title (#PCDATA)>
<!ELEMENT inscription (#PCDATA)>
<!ELEMENT verse (#PCDATA | ref | footnote)*>
<!ATTLIST verse
	number CDATA #REQUIRED
>
<!ELEMENT ref (#PCDATA)>
<!ELEMENT footnote (#PCDATA)>
<!--ELEMENT init (#PCDATA)-->
<!ELEMENT verses (title, subtitle, (inscription?, verse)*)>
<!ATTLIST verses
	nr CDATA #REQUIRED
	verse_cnt CDATA #REQUIRED
>
<!ELEMENT subtitle (#PCDATA)>

=== alvakim/spiritalph/xml/p19.xml
<?xml version="1.0" encoding="Windows-1251"?>
<!DOCTYPE chapter SYSTEM "chapter.dtd">
<?xml-stylesheet type="text/xsl" href="chapter.xsl" ?>
<chapter part="2" chapt="7" verse_cnt="10">
	<title>ГлавA седмaz</title>
	<inscription>Њ є4же блюсти1сz смёха, праздносл0віz же и3 кощyнствъ.</inscription>
	<verse number="№">Блюди1сz смёха, праздносл0віz же и3 кощyнствъ, да не сHбраннаz плaчемъ, ўд0бнэ безчи1ннымъ смёхомъ и3 кощyнствы расточи1ши: смёхъ безчи1нный сHбраннаz расточaетъ, и3 ўстранsетъ гDни бlгодaти, пaмzть смeртную погублsетъ, судA стрaшнагw забhтіе твори1тъ. Смёхъ є4сть дётска нрaва, сластолюби1ва сeрдца, слaбыz и3 немyжественныz души2 знaменіе: смёхъ всsкw непотрeбенъ є4сть.</verse>
	<verse number="в7">Блюди1сz смёха, да не раздражaеши плaча ўчaщагw тS, да не прaзденъ бyдеши всsкіz добродётели, да не њб8sтъ бyдеши пaгубнымъ през0рствомъ, и3 въ сBти діaволи впадeши. лyчшій смёха плaчь: и4бо хrт0съ не блажи1тъ смэю1щихсz, но плaчущихсz. Блажeни, речE, не смэю1щіисz, но плaчущіи, ћкw тjи ўтёшатсz: и3 пaки: г0ре смэю1щымсz, ћкw тjи восплaчутсz <ref>Матf. за? ‹</ref>: смёха бо дёлателє во џномъ вёцэ постыдsтсz, и3 во врeмz весeліz восплaчутсz и3 возрыдaютъ.</verse>
	<verse number="G">Что2 ќбw человёче, и4маши смёха, рaдости же и3 весeліz дост0йно въ мjрэ сeмъ; Что2 и4маши, њ нeмже и3звёстнw ўтэшaтисz возм0глъ бы є3си2; ПолнA жи1знь твоS ск0рби, печaли же и3 воздыхaніz: тh же въ смёхахъ и3 кощyнствахъ врeмz твоE и3знурsеши: полнA жи1знь твоS плaча и3 рыдaніz, тh же весели1шисz и3 благодeнствуеши: дёйство є4сть сE твоегw2 неразyміz. Не вёси, њ нeмже ўтэшaтисz и4маши: не вёси, ±же ти2 сyть на п0льзу, и3 на вёчное твоE приwбрётеніе. Не њ си1хъ ты2 ўтэшaйсz, но њ гDэ, њ нeмже и4маши ўтэшaтисz во вёки.</verse>
	<verse number="д7">Блюди1сz смёха, праздносл0віz же и3 кощyнствъ, да не благодaти б9іz tтщети1шисz, и3 пyсту дyшу твою2 сотвори1ши: смёхъ бо и3 кощ{нства tг0нzтъ гDню бlгодaть, ўстужaютъ сeрдце, њтzгчaютъ дyшу, помрачaютъ с0вэсть, њпечалsютъ ѓгGлwвъ, веселsтъ бэсHвъ: всsкому дерзновeнію винA, грэхY ходaтай, блудY, и3 всsкой нечистотЁ  руков0ждь и3 предводи1тель.</verse>
	<verse number="є7">Не хощи2 никогдaже что2 рещи2, и3ли2 что2 вэщaти кромЁ нyжды: t сегH бо мн0га ѕл†z раждaтисz њбык0ша: и3 пaче и3нёхъ страстeй сіS стрaсть наипaче недовёдомw и3 ўд0бнw подкрадaти њбhче: мн0гажды бо начeнше њ бGосл0вныхъ словесёхъ, прих0димъ въ сквернослHвіz, кл‰твы, и3 во вс‰ ѕл†z. Сегw2 рaди блюди1сz, да не бyдеши сaмъ себЁ навётникъ и3 врaгъ: смeрть бо и3 жив0тъ въ руцЁ љзhка є4сть, глаг0летъ соломHнъ ўдержавaющіи є3го2, снэдsтъ плоды2 є3гw2 <ref>При1тч. }i</ref>.</verse>
	<verse number="ѕ7">Молчaніе, ћкw начaло сyщее є4сть њчищeніz души2, и3 кромЁ трудA вс‰ зaпwвэди ўстроsетъ хотsщему, ћкоже нёкто речE: љзhкъ бо є4сть неудержи1мо ѕло2, и3сп0лнь ћда смертон0сна: тёмъ бlгословлsемъ бGа и3 nц7A, и3 тёмъ кленeмъ человёки <ref>Їaк. за? н7д</ref>, глаг0летъ ґпcлъ. Ѓще кто2 въ сл0вэ не согрэшaетъ, сeй совершeнъ мyжъ, си1ленъ њбуздaти и3 всE тёло. Ко глаг0ланію трeбэ є4сть nпaснства мн0га: пeрвэе съ к0имъ кто2 нрaвомъ глаг0лати и4мать, и3 к0егw врeмене, и3 что2 глаг0летъ, и3 въ кjй конeцъ и4мать бhти то2 глаг0ланіе: глаг0лzй вс‰ сі‰ д0лженъ и3мёти въ пaмzти, молчaй же вс‰ соверши1лъ и3 и3сп0лнилъ є4сть.</verse>
	<verse number="з7">Храни1сz суесл0віz, смёха же и3 кощyнствъ дaже до мaла прaздна сл0ва: и3 њ самёмъ бо прaзднэмъ сл0вэ tвётъ и4маши дaти въ дeнь судA, ћкоже гDь речE <ref>Матf. за? м7з</ref>. Сегw2 рaди и3 дв7дъ њ сeмъ къ бGу моли1тствуz глаг0лаше: положи2, гDи, хранeніе ўстHмъ мои1мъ, и3 двeрь њграждeніz w2 ўстнaхъ мои1хъ. Не ўклони2 сeрдце моE въ словесA лукaвствіz, непщевaти вины6 њ грэсёхъ <ref>Pал0мъ Rм</ref>. И# пaки: рёхъ сохраню2 пути6 моS, є4же не согрэшaти ми2 љзhкомъ мои1мъ: положи1хъ ўстHмъ мои1мъ храни1ло, внегдA востaти грёшному предо мн0ю, њнэмёхъ и3 смири1хсz и3 ўмолчaхъ <ref>Pал0мъ lи</ref>.</verse>
	<verse number="}">Почто2 и4маши ўтэшaтисz њ смёхэ и3 кощyнствахъ, ±же не сyть ти2 въ п0льзу; є3щe бо не преплhлъ є3си2 мjра сегw2 бёдъ, и3 ўжE въ смёхэ и3 кощyнствахъ ўтэшeніе своE полагaеши; не u5 плaча и3збhлъ є3си2, ґ смёхомъ и3 праздносл0віемъ ўтэшaешисz; ничт0же дост0йно рaдости въ мjрэ сeмъ и4маши, и3 смёхомъ порабощaешисz; Не вёмъ, к0егw є3си2 внимaніz: не вёси ли, ћкw вс‰ въ мjрэ сeмъ плaча достHйна, ґ не смёха, рыдaніz достHйна, ґ не рaдованіz; въ дeбрэ бо плачeвной є3си2, ґ не во ўтэшeніи: во и3згнaніи, ґ не во n§ествэ. Д0лженъ є3си2 скорбёти, ґ не весели1тисz: плaкати и3 рыдaти, ґ не смэsтисz и3 кощyнствовати.</verse>
	<verse number="f7">Погуби1вый кто2 мaлую вeщь, смущaетсz и3 скорби1тъ ѕэлw2: тh же вёчное своE o7чество покуби1въ, смэeшисz и3 весели1шисz: ни мaлw њ сeмъ скорби1ши, нижE взыскyеши: во и3згнаніи сeмъ ћкw въ вёчномъ n§ествэ простирaешисz: и3дёже ти2 плaкати и3 рыдaти дост0итъ, тaмw смэeшисz и2 весели1шисz: и3дёже пещи1сz и3 тщaтисz подобaетъ њ и3скуплeніи твоеS раб0ты, тaмw њбезпечалsешисz и3 почивaеши. Плэнeнъ кто2 въ чуждyю странY, t земли2 въ зeмлю, во врeменной раб0тэ сyщи, скорби1тъ и3 смущaетсz ѕэлw2: тh же t раS въ мjръ сeй, t животA въ смeрть, t своб0ды въ раб0ту плэнeнъ є3си2, въ вёчной раб0тэ є3си2, въ безсловeсныхъ наслёдіzхъ, въ далечaйшей странЁ сhй, не чyвствуеши: њ своeмъ ми1рномъ, люби1момъ, своб0дномъ, вёчномъ n§ествэ не скорби1ши: њ и3скуплeніи и3 свобождeніи не печeшисz, и3 не чyвствуеши: дёйство є4сть сE твоегw2 неразyміz и3 слэпоты2.</verse>
	<verse number="‹">Тёмже блюди1сz смёха, да не плaчь вёчный пости1гнетъ тS: блюди1сz праздносл0віz и3 кощyнствъ, да не по сeмъ ѕэлw2 раскaешисz, є3гдA во и3сх0дэ души2 своеS нищетY ќзриши: да не тогдA раскaешисz, є3гдA ничт0же себЁ помощи2 возм0жеши. q дабы2 є3си2 познaлъ! q дабы2 є3си2 ўвёдалъ, что2 и4мать бhти по си1хъ! никогдaже въ чeмъ безпечалsтисz восхотёлъ бы є3си2: никогдaже въ смёхэ и3 кощyнствахъ врeмz своE и3знурsлъ бы є3си2. Смэsхусz џни, и5же днeсь плaчутъ, рaдовахусz џни, и5же днeсь рыдaютъ, нижE рыдaти когдA престaнутъ. По насыщeніи трапeзномъ наипaче смёха блюди1сz: тогдa бо џнъ наипaче приходи1ти wбhче: ѓще же и3 случи1ттисz когдA въ сeмъ поползнyтисz, но кромЁ ѕёльнагw раскazніz никогдaже тогw2 њстaви.</verse>
</chapter>

=== alvakim/spiritalph/xml/p17.xml
<?xml version="1.0" encoding="Windows-1251"?>
<!DOCTYPE chapter SYSTEM "chapter.dtd">
<?xml-stylesheet type="text/xsl" href="chapter.xsl" ?>
<chapter part="2" chapt="5" verse_cnt="10">
	<title>ГлавA пsтаz</title>
	<inscription>Њ є4же ни мaло что2 њ себЁ мнёти.</inscription>
	<verse number="№">Не бyди ўловлsемь самомнёніемъ и3 высокомyдріемъ, мнS t себe и3ли2 соб0ю сотвори1ти что2 блaго: t тебe бо ничт0же блaго кромЁ п0мощи б9іz происходи1ти м0жетъ, т0чію вс‰ ѕл†z, всsкъ грёхъ, понeже въ беззак0ніи зачaтъ є3си2, и3 во грэсёхъ роди1 тz мaти въ мjръ <ref>Pал0мъ н7</ref>. Ничт0же и4маши t себE ѓще не t гDа: ћкоже сaмъ t себE нёси, си1це ни t себE что2 блaго и3мёти м0жеши. сегw2 рaди не мни2 њ себЁ ничт0же: мнs бо себE бhти что2, ничт0же сhй, себE льсти1тъ, глаг0летъ ґпcлъ <ref>Галaт. за? сд7i</ref>.</verse>
	<verse number="в7">Ѓще и3 предложeніе и3мёти бyдеши благ0е, но грэхY кромЁ п0мощи б9іz соб0ю сопроти1въ стaти, и3 побэди1ти є3гw2 не м0жеши: понeже преступлeніz рaди t рождeиіz твоегw2 подпaлъ є3си2 под8 и4го и3 раб0ту грэхA: тогw2 рaди соб0ю своб0дь є3гw2 бhти не м0жеши, ѓще не гDь пом0жетъ ти2 и3 ўкрэпи1тъ тS. nбaче ты2 t себE и3 предложeніz благaгw и3мёти не м0жеши, ѓще не гDь благодaтію своeю предвари1тъ є5. ћкоже и3ст0чницы воднjи, ѓще не и3спyстzтъ воды2, не востекyтъ рёки: си1це и3 не поспэшествyющей гDни блгdти, вс‰ њстaнутъ пр†здна.</verse>
	<verse number="G">Ћкоже вBтви ничт0же t себE раждaти м0гутъ кромЁ к0рене: си1це нижE ты2 что2 блaго и3зв0лиши и3ли2 содёеши кромЁ б9іz благодaти. ГDь є4сть к0рень, тh же розгA. Дот0лэ что2 бGоуг0дно твори1ти м0жеши, донeлэ съ бGомъ є3си2: є3гдa же t бGа tлучи1шисz, тогдA во вс‰ ѕл†z впадeши. Ћкоже розгA не м0жетъ плодA сотвори1ти њ себЁ, ѓще не бyдетъ на лозЁ: тaкw и3 мы2, ѓще въ гDэ не пребyдемъ. Без8 менe бо не м0жете ничесHже твори1ти, речE гDь <ref>Їwaн. за? }</ref>: џнъ бо є4сть к0рень и3 и3ст0чникъ всsкагw блaга.</verse>
	<verse number="д7">Кaкw возм0жеши что2 бGоуг0дно сотвори1ти, съ бGомъ предолжeніемъ не соединszсz, ни въ слaву є3гw2 что2 творS. Ѓще что2 и3 бhло бы мни1мо блaго, не съ бGомъ же, нёсть сіE блaго, понeже не съ бGомъ, ни во слaву є3гw2. мн0зи t себE мнsтсz твори1ти что2 бlго, но t гDа непріsтно: понeже не съ бGомъ, ни во слaву б9ію. всsко благ0е не м0жетъ бhти благи1мъ, ѓще не съ гDемъ: нижE ѕл0е ѕлhмъ, ѓще не кромЁ гDа: џнъ бо є4сть всемY благ0му начaло, и3 конeцъ безконeчный.</verse>
	<verse number="є7">Никт0же въ прaвду м0жетъ твори1ти, не т0чію блaго, но нижE ѕло2, кромЁ б9іz попущeніz, и3 благ0му пос0бствованіz. Џнъ бо вс‰ сотвори2, и3 во влaсти своeй вс‰ содeржитъ. Но ѓще кто2 что2 ѕло2 твори1тъ, не п0мощію б9іею, ни благоволeніемъ є3гw2 твори1тъ, но т0чію самовлaстіемъ и3 попущeніемъ: бGъ бо ѕлY нёсть помогaтель помогaтель, но благ0му: nбaче же , ћкоже ѕл0му въ ѕлhхъ и3ногдA содёzти что2 ѕло2 попущaетъ, и3ногдA же и3 возбранsетъ свои1мъ смотрeніемъ: си1це и3 благ0му и3 препинaетъ и3ногдA, и3 пос0бствуетъ, ћкw да nбои1хъ ѕлhхъ же и3 благи1хъ и3скyситсz самовлaстное предложeніе, и3 познaетсz б9eственнаz влaсть и3 держaва.</verse>
	<verse number="ѕ7">Не всsкое ѕло2 ѕлhй содёzти м0жетъ кромЁ б9іz попущeніz, нижE благjй благ0е кромЁ помогaніz. Ѓще и3 самовлaстіемъ к0ждо t бGа почтeнъ є4сть, и3 не т0чію человёцы, но и3 бёси и4мутъ своE намёреніе, и3 предBлъ свои1хъ прескакaти не м0гутъ: но џвому въ ѕлhхъ, ћкоже вёсть, благосл0вныхъ рaди ви1нъ мн0гажды не попущaетъ: џвому же во благи1хъ не пос0бствуетъ: ћкw да п0мощи є3гw2 трeбуz ўбэжи1тъ мнёніz, и3 познавaz свою2 нeмощь, ћкw t себE ничт0же и4мать, пребyдетъ всегдA смирszсz.</verse>
	<verse number="з7">Ћкоже ѕл0му мн0гажды не всsко ѕло2 благосл0вныхъ рaди ви1нъ попущaетъ, си1це нижE благ0му благ0е: nбои1хъ же предложeніе въ дёло написyетъ. Ѓще бо бы2 ѕлhй всE ѕл0е, благjй же всE благ0е, кромЁ попущeніz б9іz, и3 бlг0му помогaніz возм0глъ бы, никт0же ни въ чeмже п0мощи б9іz желaлъ бы, никт0же њ мlтвэ и3 молeніи радёлъ бы: но всE кjйждо по в0ли своeй твори1лъ бы, ничт0же смотрeніе бGа премышлsющагw и3 њбладaющагw мнёлъ бы бhти, ни въ чeмъ влaсти рaзность творцY t твaри былa бы. Сегw2 рaди не вели1ка себE разумёй бhти, но мни2, ћкw ничт0же є4си2: мнsй бо себE бhти что2, себE льсти1тъ, слёпъ сhй душeю, непросвэщeнъ въ рaзумэ, и3 не вёсть, кaмw и4детъ.</verse>
	<verse number="}">Ѓще не гDь сози1ждетъ д0мъ, всyе труди1шасz зи1ждущіи: ѓще не гDь сохрани1тъ грaдъ, всyе бдЁ стрегjй, гlетъ прbр0къ <ref>Pал0мъ рк7ѕ</ref>. Тщи1сz ты2, и3 трезви1сz во благ0мъ, на себe же ўповaніz не полагaй, но бGу молsсz п0мощи є3гw2 ўсeрднэ всегдA взыскyй. Ѓще пом0жетъ ти2, и3 поспэши1тъ ти2 гDь, соверши1тсz дёло, ѓще ли ни2, вс‰ тво‰ разсhплютсz. Ѓще бы что2 и3 бhло мни1мо твоE блaго, t гDа же бyдетъ не пріsтно, кaz ти2 є4сть п0льза; Ѓще бы и3 восхотёлъ є3си2 въ возношeніи твоeмъ чи1мъ мни1мымъ свои1мъ пред8 гDемъ ўдобри1тисz, џнъ же не пріи1метъ, что2 себЁ пом0жеши; но речeтъ ти2: дрyже, не њби1жу тебE, возми2 своE, и3 и3ди2 по при1тчи є3ђльской <ref>Матf. за? п7</ref>. Сегw2 рaди вс‰ и3справлє1ніz нaша, не си1це въ нaсъ сyть, ћкоже въ ми1лости хrт0вой. Ѓще себE мни1ши бhти что2, сегw2 рaди пред8 ни1мъ ничт0же є3си2, понeже себE си1це бhти разумёеши. Ѓще себE разyмна и3 бlгопотрeбна бhти мhслиши, сегw2 рaди весмA непотрeбенъ є3си2. Ѓще себE чи1ста и3 прaведна и3 свsта разумёеши, сегw2 рaди nкаsннэйшій, и3 грёшнэйшій пaче всёхъ человBкъ пред8 гDемъ вмэнsешисz, понeже себE си1це разумёеши: нечи1стъ бо пред8 гDемъ всsкъ высокосeрдый, гlетъ соломHнъ <ref>При1тчей ѕ7i</ref>.</verse>
	<verse number="f7">Сегw2 рaди бyди смирeнъ, разумёй свою2 нeмощь: пaмzтствуй, ћкw вс‰ сyтъ б9іz, ґ не нaша, вс‰ t бGа сyть, ґ не t тебE, всsко даsніе бlго и3 всsкъ дaръ совершeнъ , свhше є4сть, сходsй t nц7A свётwвъ, глаг0летъ ґпcлъ <ref>Їaкw+ за? }</ref>. Пaмzтствуй, ћкw всE въ ми1лости хrт0вой є4сть, ґ не въ твоeй си1лэ и3 влaсти: пaмzтствуй, ћкw в0лею и3 нев0лею ко грэхY преклонeнъ є3си2: вёси, ћкw кромЁ п0мощи б9іz и3 є3гw2 бlгодaти ћкw паучи1ннаz сёть. Не бyди г0рдъ и3 самомни1теленъ, да не ўпод0бишисz бёсу: бёсъ бо си1мъ t бGа tпадE. ћкw вс‰ себЁ причитовaше, бGу же вс‰ сотв0ршему ничт0же: сегw2 рaди всегw2 tпадE, и3 њбнажи1сz гDни бlгодaти, и3 вёчному томлeнію пред8угот0ва себE сосyдъ. Не мни2 себE бhти прaведна и3 свsта, премyдра и3 всsкіz чeсти дост0йна: не мни2 себE лyчша и3 благопотрeбнэйша и3нёхъ, но пaче всёхъ грёшнэйша и3 безyмнэйша, и3 неключи1ма бhти себE вмэнsй: тh бо пред8 бGомъ без8 смирeніz ничт0же є3си2: преспёzніе бо смирeніz, є4сть преспёzніе добродётели и3 всsкагw и3справлeніz.</verse>
	<verse number="‹">Не бyди њ себЁ высокомyдрствуzй, мнS, ћкw ты2 є3ди1нъ свои1мъ рaзумомъ и3 премyдростію всёхъ превозшeлъ є3си2, и3 вс‰ є3ди1нъ сaмъ њб8sти могjй: но внемли2, ћкw вeлій є4сть мjръ, и3 вси2 концы2 земли2, въ ни1хже разли1чныхъ во nбои1хъ сaнахъ ли1цъ, д¦0вныхъ и3 мірски1хъ, неисчeтное мн0жество премyдрыхъ и3 разyмныхъ, всsкагw препод0біz и3 чeсти дост0йныхъ њбрэтaетсz, и5хже бlгодaть прес™aгw д¦а пречyднэ ўпремyдри, и3 разли1чнэ ў3добри2, и5мже ты2 ни въ слёдъ шeствовалъ є3си2, и5хже ты2 не вёси, нижE рaзумомъ твои1мъ пости1гнути м0жеши, коли1кw є4сть безчи1сленное мн0жество тмaми тє1мъ во всeмъ превосходsщихъ тебE. Бёгаzй мни1тъ, ћкw скорёе всёхъ течeтъ сaмъ, є3гдa же со и3нёми спрzжeтсz, тогдA познавaетъ свою2 нeмощь.</verse>
</chapter>

=== alvakim/spiritalph/xml/p5.xml
<?xml version="1.0" encoding="Windows-1251"?>
<!DOCTYPE chapter SYSTEM "chapter.dtd">
<?xml-stylesheet type="text/xsl" href="chapter.xsl" ?>
<chapter part="1" chapt="5" verse_cnt="10">
	<title>ГлавA пsтаz</title>
	<inscription>Њ є4же во всeмъ послёдовати рaзуму, и3 разсуждeнію, нeже безсловeсной пл0ти.</inscription>
	<verse number="№">Пред8 всёми вещми2 и3 во всёхъ вeщехъ да предварsетъ и3 предх0дитъ пред8 тоб0ю всегдA прaвъ рaзумъ, и3 разсуждeніе: и3 никогдaже ни въ чeмъ прельсти1шисz, но пaче всёхъ прeлестей превhшше бyдеши. ћкоже внёшніz вс‰ вє1щи не м0гутъ бhти зри1мы, т0чію nчи1ма, си1це нижE вн{треннzz д¦Hвнаz м0гутъ бhти разумBнна, т0чію рaзумомъ и3 ќмнымъ разсмотрeніемъ.</verse>
	<verse number="в7">Да не начинaеши, нижE что2 когдA дёеши, д0ндеже бGу моли1твою соединszйсz, разсyдиши: ничт0же бо си1це во всёхъ вeщехъ непреткновeнна, и3 непоползновeнна человёка твори1ти њбhче, ћкоже прaвъ рaзумъ и3 разсуждeніе. Да смhслиши њ всёхъ, ±же ѓще дёеши, речE ко їисyсу наvjну гDь <ref>Їисуc Наv=. гл+а №</ref>.</verse>
	<verse number="G">Ћкоже не безбёднw слэпhй шeствуетъ, си1це нижE безyмный что2 твори1тъ блaго: сегw2 рaди не повинyйсz плотстёй п0хоти и3 желaнію, но т0чію во всёхъ вeщехъ рaзуму и3 разсуждeнію всегдA послёдуй. </verse>
	<verse number="д7">Пeрвэйшаz винA бhсть ґдaмлю падeнію, ћкоже рек0хъ, безyміе: ѓще бы предразсуди1лъ себЁ заповёданіе, ѓще бы послёдовалъ рaзуму, не бы2 преслyшалъ, не бы2 вкушeніемъ дрeва заповёданнагw прельсти1лсz.</verse>
	<verse number="є7">Никт0же м0жетъ пaсти, и3 согрэши1ти, рaзуму и3 разсуждeнію послёдуz: нижE содёzти что2 блaго, не и3мёzй прaвагw рaзума. Ћкоже начaло и3 к0рень всsкому грэхY безyміе є4сть, и3 безсловeсное себE непознaніе, си1це и3 начaло всsкому блaгу прaвъ рaзумъ и3 разсуждeніе.</verse>
	<verse number="ѕ7">Слэпhй внёшнима nчи1ма во всёхъ стезsхъ свои1хъ мн0гажды и3 разли1чнw претыкaетсz, си1це и3 не и3мёzй прaвагw рaзума, ниже слёдуz разсуждeнію, во тмЁ неразyміz и3 грэхA всегдA шeствуетъ, познaвый же себE, и3 зрsй мhсленный свётъ, всегдA во всeмъ непреткновeнъ є4сть.</verse>
	<verse number="з7">Чт0 є3сть грёхъ; т0чію плотскjz п0хоти дёйствіе. плотскjz же п0хоти дёйствіе, чт0 є3сть; Ничт0же и4но, т0чію безyміе: и3 никт0же согрэши2, т0чію въ безyміи и3 неразсуждeніи: нижE содёетъ что2 блaго, т0чію въ рaзумэ: нижE что2 ѕл0е, ѓще не въ безyміи.</verse>
	<verse number="}">Всsкагw грэхA всегдA предварsетъ безyміе, дободётели же и3 благодэ‰ніz рaзумъ, не дaруетъ никогдaже безyміе человёку пок0z, нижE совершeннагw ўтэшeніz, ѓще не сaмъ рaзумъ ўпок0итъ, и3 просвэщeніемъ свои1мъ ўтёшитъ дyшу. Ћкоже бо слэп0му не м0щно и3мёти пок0z, донeдлэ не зри1тъ свёта, си1це ни безyмному, д0ндеже не пріи1детъ въ рaзумъ.</verse>
	<verse number="f7">Тёмже пaче всёхъ добродётелей да предпочтeни бyдутъ, рaзумъ и3 разсуждeніе: сe бо є4сть начaло и3 винA всемY благ0му. ни бо2 добродётель добродётелію, ћкw подобaетъ, бhти м0жетъ, ѓще разсуждeніе и3 рaзумъ спомогaтеленъ и3 предводи1теленъ дёлу не бyдетъ.</verse>
	<verse number="‹">Ћкоже всёхъ є3стeственныхъ чyвствъ, честнёйшее и3 рaдостнэйшее є4сть въ ви1димыхъ зрeніе, си1це и3 въ мhсленныхъ разумэвaемыхъ, честнёйшій и3 ўтёшнэйшій є4сть рaзумъ, и3 всёхъ вещeй познaніе: сe бо є4сть и3 жив0тъ вёчный, сe же и3 tпадeніе, и3 пріsтіе томлeніz.</verse>
</chapter>

=== alvakim/spiritalph/xml/p3.xml
<?xml version="1.0" encoding="Windows-1251"?>
<!DOCTYPE chapter SYSTEM "chapter.dtd">
<?xml-stylesheet type="text/xsl" href="chapter.xsl" ?>
<chapter part="1" chapt="3" verse_cnt="10">
	<title>ГлавA трeтіz</title>
	<inscription>Њ є4же не дёлаzй кто2 рaзумомъ, и3 не њчищazй є3гw2, не прaвъ и3 не и4стиненъ є4сть рaзумъ.</inscription>
	<verse number="№">Рaзумъ недёланъ, и3 д0лгимъ врeменемъ не њчищeнъ, рaзумъ не разyменъ є4сть, не прaвъ и3 не и4стиненъ є4сть рaзумъ. Е$сть же рaзума разли1чіе, ћкоже и3 всёхъ внёшнихъ вещeй. Е$сть бо рaзумъ совершeнъ, дух0венъ, є4сть же посрeдній, дш7eвенъ, є4сть же tню1дъ грyбъ, плотскjй. Ћкоже ќбw внёшнzгw ўчeніz, и3ли2 к0егw худ0жества, никт0же навhкнетъ, не всегдA њ нeмъ поучazсz и3 попечeніе творS: си1це и3 совершeннагw д¦0внагw рaзума и3 њчищeніz ќмнагw кто2 и3зучи1тсz, не всегдA њ сeмъ прилэжaніе творS;</verse>
	<verse number="в7">Не потщaвыйсz кто2 пройти2 соб0ю тёсный пyть є3ђльскій, и3 њ њчищeніи ўмA вознебрeгъ, ѓще и3 всю2 внёшнюю мyдрость и3звhче, слёпъ є4сть душeю: писмA т0чію ўбивaтельнагw придержи1тсz, д¦а же њживлsющагw не пріeмлетъ: и3 не т0чію и3нёхъ, но нижE себE совершeннw и3спрaвити м0жетъ. И$нъ бо є4сть рaзумъ мjра сегw2, и4нъ же є4сть д¦0венъ: д¦0внаго бо рaзума t прес™aгw д¦а ўчи1шасz вси2 с™jи, и3 просвэти1шасz ћкw сlнце въ мjрэ. Днeсь же не t д¦а с™а, но t ґріст0телz, цицер0на, платHна, и3 пр0чіихъ kзhческихъ любомyдрцєвъ рaзума ўчaтсz. Сегw2 рaди до концA њслэп0ша лжeю, и3 прельсти1шасz t пути2 прaвагw въ рaзумэ. С™jи зaповэдей хrт0выхъ, и3 ќмнагw дёланіz ўчи1шасz: сjи же т0чію словeсъ и3зглаг0ланій ўчaтсz: внyтрь души2 мрaкъ и3 тмA, на љзhцэ же всS и4хъ премyдрость.</verse>
	<verse number="G">Не м0жетъ прaвъ и3 и4стиненъ рaзумъ, ўд0бь въ дyшу бhти ўглублeнъ, ѓще не д0лгимъ врeменемъ, и3 ѕёлнымъ труд0мъ, и3 п0двигомъ, и3 тaкw по мёрэ п0двига и3 трудA, ўмерщвлsютсz плотскjz п0хwти, и3 по є3ли1ку ўмерщвлsютсz п0хwти, по толи1ку процвэтaетъ и3 возрастaетъ и4стиненъ рaзумъ. Сугyбагw же всBмъ трeбэ є4сть п0двига, ћкоже внёшнzгw трудA, си1це и3 дёланіz ќмнагw: є3ди1нъ бо кромЁ другaгw не совершaетсz.</verse>
	<verse number="д7">Навhкнувый кто2 внёшніz мyдрости, д¦0вную же вознебрeгъ, под0бенъ є4сть њ є3ди1номъ џцэ, и3ли2 њ є3ди1ной нозЁ сyщему. Внёшнzz мjра сегw2 мyдрость и3 тэлeсный трyдъ, кромЁ ќмнагw дёланіz, ћкw сосцы2 сyхи, ћкw дрeво неплодови1то, глаг0летъ нёкто. Тогw2 рaди не преставaху с™jи, на є3ди1номъ внёшнемъ т0чію трудЁ и3 ўчeніи, но потщaшасz навhкнути и3 внyтреннzгw, си1рэчь њчищeніz ќмнагw. Ѓще бы во внёшнемъ ўчeніи т0чію бhли ўчи1лисz, въ д¦0вномъ же ни2, не бhли бы свsти, нижE блгdть прес™aгw д¦а пребывaла бы въ душaхъ и4хъ.</verse>
	<verse number="є7">Вси2 є3ли1цы внёшнzгw наказaніz навhкше, њ д¦0вномъ внyтреннемъ дёланіи, њ њчищeніи и3 просвэщeніи рaзума неради1ша, всеконeчнw њбезуми1шасz, и3 разврати1шасz въ разли1чныz стр†сти, и3ли2 въ є4рєси поги1бельныz впад0ша, ћкоже ѓрій, савeллій, є3vтjхій, и3 пр0чіи мн0зи, и5же не и3скуси1ша, ни познaша бGа и3мёти во своeмъ рaзумэ: сегw2 рaди предадE и5хъ бGъ въ неискyсенъ ќмъ, твори1ти неподHбнаz, глаг0летъ ґпcлъ <ref>Ри1м. за? п7а</ref>.</verse>
	<verse number="ѕ7">Ѓще кто2 и3 всю2 мyдрость мjра сегw2 и3звhкнетъ, не њчи1ститъ же ўмA, нижE просвэти1тсz душeю, бGу соедини1тисz не возм0жетъ. Не соедини1выйсz же гDви въ рaзумэ д¦омъ, въ стезsхъ безвёстныхъ є4сть. њчищaетсz же и3 просвэщaетсz ќмъ сугyбымъ п0двигомъ, ћкоже рек0хъ: хранeніемъ гDнихъ зaповэдей, и3 ќмнымъ всегдaшнимъ дёланіемъ, пaче же всегдaшними тeплыми слезaми. И#нaкw бо до просвэщeніz ќмнагw никт0же пріити2 возм0жетъ.</verse>
	<verse number="з7">Всsкъ ќмъ не дёланъ, не просвэщeнъ, не њсолeнъ бhвши с0лію блгdодaти прес™aгw д¦а, њбезуми1тсz, и3 разли1чными стрaстными дэsнми и3 помышлeньми возсмерди1тсz. Рaзумъ бо комyждо є3стeственнw t гDа всаждeнъ є4сть, nбaче не дёлаzй кто2 и4мъ, помрачaетсz и3 потемнэвaетъ: дёлаzй же ўzснsетсz, и3 въ совершeнное просвэщeніе прих0дитъ.</verse>
	<verse number="}">Ћкоже и3 малёйшее nтрочA, не трeбуетъ ўчeніz, тэлeсныма nчи1ма зрёти свётъ, (ѓще не недyжно є4сть зрёніемъ) си1це не трeбуетъ кто2 и3 внёшнzгw ўчeніz ко премyдрости д¦0внэй, и3 соединeнію рaзумомъ гDви, т0чію њчищeніz и3 просвэщeніz ќмнагw. Мн0зи бо не т0чію внёшнzгw ўчeніz неискyсни, но и3 tню1дъ препр0сти бhвше, премyдрости д¦0вныz ќмнымъ дёланіемъ и3 хранeніемъ гDнихъ зaповэдей научи1шасz, и3 вели1кимъ дарHмъ прич†стницы бhша, ћкоже ґнтHній, пахHмій, пavелъ препр0стый, и3 и3нjи.</verse>
	<verse number="f7">Пeрвэйшій є4сть ќмъ пaче ўчeніz внёшнzгw и3 пи1смене. Не бо2 t пи1смене, и3 ўчeніz внёшнzгw њбрётесz и3 возрастE ќмъ: но t ўмA вс‰ сі‰ роди1шасz и3 возраст0ша. БGъ є3стeственнw ќмъ комyждо дадE, внёшнzгw же ўчeніz рaзумъ t человBкъ прибhсть: тогw2 рaди пaче всёхъ, д0лжни є3смы2 и3мёти тщaніе њ њчищeніи рaзума. Ќмъ њчищeнъ и3 просвэщeнъ бhвши, всS внBшнzz и3 вн{треннzz разумёти и3 востzзaти м0жетъ: д¦0венъ бо, востzзyетъ ќбw вс‰, ґ сaмъ т0й ни t є3ди1нагw востzзyетсz, речE ґпcлъ <ref>Ко> за? рк7з</ref>.</verse>
	<verse number="‹">Всsка жeртва с0лію њсоли1тсz, речE гDь: не њсоленA же бhвши возсмерди1тсz <ref>Ма> за? м7в</ref>. Си1це и3 душA, є4сть св0йственна бGу жeртва, по рeкшему: жeртва бGу д¦ъ сокрушeнъ <ref>Pал0мъ н7</ref>. не њсоленa же бhвши с0лію блгdти прес™aгw  д¦а, всsкw возсмерди1тсz безyміемъ, и3 и3сп0лнитсz разли1чныхъ страстeй. Ѓще и3 всю2 мyдрость мjра сегw2 кто2 и3звhкнетъ, не њсоли1тсz же с0лію с™aгw д¦а, и3 не бyдетъ причaстенъ гDни бlгодaти, весьмA непотрeбенъ пребyдетъ, ћкоже не и3мёzй въ себЁ начертaнна џбраза цrка, внЁ и3змeщетсz черт0га хrт0ва: ѓще кто2, речE, д¦а хrт0ва не и4мать, сeй нёсть є3гw2 , глаг0летъ ґпcлъ <ref>Рим. за? §ѕ</ref>.</verse>
</chapter>

=== alvakim/spiritalph/xml/p31.xml
<?xml version="1.0" encoding="Windows-1251"?>
<!-- edited with XML Spy v3.5 NT (http://www.xmlspy.com) by alakim (mai) -->
<!DOCTYPE chapter SYSTEM "chapter.dtd">
<?xml-stylesheet type="text/xsl" href="chapter.xsl" ?>
<chapter part="3" chapt="9" verse_cnt="10">
	<title>ГлавA девsтаz</title>
	<inscription>Њ є4же возбуждaти себE всегдA ко ўсeрдствованію и3 теплотЁ гDней.</inscription>
	<verse number="№">Пріиди2, q человёче! и3 ви1ждь: пріиди2, гDа своего2 прослaви, пріиди2, гDа своего2 восп0й, пріиди2, припади2 пред8 гDемъ, и3 восплaчисz пред8 сотв0ршимъ тS <ref>Pал0мъ §д</ref>: пріиди2, припади2, и3 и3сповёждьсz пресвzт0му є3гw2 и4мени: вкуси2, и3 ўвёждь ћкw бlгъ гDь <ref>Pал0мъ lг</ref>, п0й и4мени є3гw2, ћкw добро2.</verse>
	<verse number="в7">Пріиди2 ѓлчущій и3 жaждущій2, насhтисz бжcтвенныz пи1щи пріиди2 њмрачeнный, наслади1сz присносyщнагw свёта: пріиди1 во ќзахъ сhй, наслади1сz своб0ды: пріиди2 смeртный, прилэпи1сz безсмeртному, да вёчныz смeрти и3збyдеши, и3 животA2 вёчнагw спод0бишисz.</verse>
	<verse number="G">Пріиди2 ск0рбный и3 печaльный, наслади1сz пrносyщныz рaдости: пріиди2 ўнhлый и3 њкаменeнный, да разжeшисz ћкw џгнь: пріиди2 ни1щій, да њбогати1шисz вёчнымъ богaтствомъ: пріиди2 наги1й, да њблечeшисz безсмeртною слaвою, и3 њдёешисz ћкw ри1зою свётомъ благодaти гDни.</verse>
	<verse number="д7">Воспрzни2, воспрzни2, q человёче! и3 и3стрезви1сz, воспрzни2 и3 припади2 ко гDу бGу сотв0ршему тS. возставлsй своS ч{вства, и3 возжизaй свэти1льникъ сeрдца твоегw2, да не когдA въ тебЁ ўгaснетъ, и3 њстaвитъ тS во тмЁ нечyвствіz.</verse>
	<verse number="є7">Развeрзи, развeрзи, q человёче! дyшу на пріsтіе гDа слaвы: сe бо судіS стои1тъ при двeрехъ твоегw2 с®ца, и3 толчeтъ, ћкw да tвeрзеши є3мY, и3 вни1детъ къ тебЁ, и3 ћстъ съ тоб0ю, и3 пребyдетъ съ душeю твоeю во вёки вэкHвъ, никогдA t тебE tлучazсz.</verse>
	<verse number="ѕ7">Возставлsй ќбw человёче, возставлsй вс‰ сво‰ ч{вства, воспрzни2 не лэнsщисz и3 не ўнывaющи, не пощади2 пл0ти, не пощади2 души2, да вэнцeмъ нетлёніz ўвzзeшисz. Возводи2 џчи твои2 къ бGу, и3 ўви1ждь є3гw2 блaгость, и3 всE є4же њ тебЁ тaинство. </verse>
	<verse number="з7">Не презирaй дaннагw ти2 врeмене на стzжaніе вёчныхъ бл†гъ: сe бо грzдeтъ гDь ск0рw на џблацэхъ, со слaвою и3 си1лою мн0гою, воздaти комyждо по дэлHмъ є3гw2, и3 ќзритъ є3го2 всsко џко, и3 и5же є3го2 пробод0ша, и3 плaчь сотворsтъ на сS њ нeмъ всS колBна земнaz: сE пріи1детъ ск0рw <ref>Ґпокaл: гл+а №</ref>. Блажeнъ соблюдazй зaпwвэди гDни, блажeнъ хранsй є3гw2 зaпwвэди: пріи1детъ бо, пріи1детъ и3 не ўмeдлитъ.</verse>
	<verse number="}">Возводи2, возводи2 ќмныz џчи сeрдца твоегw2 къ бGу, q человёче и3 разжизaй своE сeрдце къ бжcтвенной є3гw2 любви2, возбуждaй свою2 дyшу къ б9eственному є3гw2 желaнію, вопjй безпрестaни къ бGу, под0бzсz слэпцY: сн7е дв7довъ, сн7е б9ій поми1луй мS, ўщeдри мS, вразуми1 мz, научи1 мz в0ли твоеS с™hz, зaповэдей твои1хъ, и3 жи1въ бyду.</verse>
	<verse number="f7">Въ бз7э всE желaніе своE и3 похотёніе да и4маши, въ бз7э всE ўповaніе и3 надeжду да полагaеши, тaмw вeсь да пасeшисz, тaмw весь всегдA да пребывaеши, до негHже концA сотворeнъ є3си2, тaмw да спэши1шисz дeнь и3 н0щь, ни мaла даS себЁ пок0z и3 њпочивaніz, д0ндеже получи1ши и3ск0мое, д0ндеже њбрsщеши мёсто гDви, селeніе бGу їaкwвлю <ref>Pал0мъ рlа</ref>.</verse>
	<verse number="‹">Да ничт0же тS tт0ргнетъ, да ничт0же ти2 препнeтъ, да ничт0же ти2 возбрани1тъ, да ничт0же тS tсэчeтъ t гDни любвE и3 бжcтвеннагw є3гw2 желaніz, ни ск0рбь, ни тэснотA, ни глaдъ, ни гонeніе, ни џгнь, ни мeчь: т0й бо є4сть тв0й жив0тъ. То2й твоE є4сть спасeніе, то2й твоS рaдость и3 весeліе, и3 присносyщное наслаждeніе и3 вёчный пок0й.</verse>
</chapter>
